### ISSUE TITLE
Add make test

### ISSUE THREAD

**Issue by decibel** [theory/pgtap#112]
I get tired of the `make install installcheck` dance... any opposition to adding a `make test` target, similar to https://github.com/decibel/pgxntool/blob/master/base.mk#L86-L92 ?

**Comment by theory** [comment]
There used to be one. The one objection is that it won't work on 8.3 or older, as a ]C module implementing pg_typeof()`](/theory/pgtap/blob/master/src/pgtap.c) needs to be compiled and installed.

**Comment by cbandy** [comment]
/me pops in to point out that 8.3 reached EOL 3.5 years ago.
/me returns to lurking.

**Comment by theory** [comment]
Yeah, people still use it, though. People be cray.

**Comment by decibel** [comment]
Uh... why would that prevent having a make test target?

**Comment by theory** [comment]
You have to install the C module before you can test with it on 8.3 or earlier. But it should be fine for 8.4 and later. In fact, I thought I had a test target at one time, which was just `pg_prove test/sql/*.sql` or some such. Don't know why I removed it…

Wait, I didn't, it's [right here](/theory/pgtap/blob/master/Makefile#L150).

**Comment by decibel** [comment]
And so it is... dur...I think it needs to be marked as .PHONY though; on my machine it thinks it's already been run.
