### ISSUE TITLE
has_extensions(NAME[], text) is broken

### ISSUE THREAD

**Issue by decibel** [theory/pgtap#121]
AFAIK, $SUBJECT should only be pulling extensions that are in schemas on the search_path, but that's not what's happening. This step in test/sql/extension.sql should fail:

```
        extensions_are( ARRAY['citext', 'isn', 'ltree', 'plpgsql'], 'Got em' ),
```

because the only extensions installed in public are citext and plpgsql.

(BTW, it would be safer if that test set an explicit search_path, since you may not know what extensions have been installed to public.)

**Comment by decibel** [comment]
@rodo would you have time to create a fix for this?

**Comment by rodo** [comment]
I'll have time next week, planned to work on pgtap between some pgconfeu conference

**Comment by rodo** [comment]
The doc says :

> This function tests that all of the extensions in the named schema, or that are visible in the search path, are only the extensions that should be there. If the :schema argument is omitted, all extensions will be checked. If the description is omitted, a generally useful default description will be generated. Example:

So what's wrong by output all extensions in all schema and not only them in search_path when schema is omitted ?

**Comment by decibel** [comment]
My concern is that this is radically different from how all the other functions work; namely that if you omit the schema you end up with search_path semantics.

Certainly schemas work differently with extensions though: extensions don't technically belong to a schema, they only make use of one if assigned. So maybe the solution here is to treat schema as an attribute of the extension, instead of where the extension is theoretically living (and as part of that, make the convention has_extensions(name[], schema, description)).

**Comment by theory** [comment]
Since there's no `pg_extension_is_visible()` function, ([reference](https://www.postgresql.org/docs/9.6/static/functions-info.html)), ISTM that it would just look at all extensions if no schema is specified.

**Comment by decibel** [comment]
I suspect that doesn't exist because extensions don't actually belong to a schema,they may (or may not) have created objects in one. So schema is really an attribute of an extension, as opposed to where the extension lives. The extension name, by itself, has to be unique.

So it's very different from all the other functions that make schema optional.

So at this point, my concern isn't actually with the no-schema version, but the version that allows you to specify a schema. That's (understandably) setup like all the other functions that test for objects that reside *in* a schema, but that just doesn't apply to extensions.

But, that's just my opinion, so if both of you think it's fine as is then we can just close this.

**Comment by theory** [comment]
Yes, you're right. Fundamentally, extensions are not associated with a schema, but they might have an attribute that defines the schema in which their objects should be created.

However, since `has_extensions()` already exists and has an optional `:schema` parameter that effectively tests for this, it makes sense to me that `has_extension()` would continue that pattern. we should just document it as such.

Well, maybe. The [docs for `extensions_are()`](http://pgtap.org/documentation.html#extensions_are) says:

>  If the `:schema` argument is omitted, all extensions will be checked.

I wonder what that means, since [the implementation](https://github.com/theory/pgtap/blob/master/sql/pgtap.sql.in#L9679) is just:

    SELECT extname FROM pg_catalog.pg_extension

So maybe the docs need some updating.

**Comment by decibel** [comment]
On 11/10/16 6:47 PM, David E. Wheeler wrote:
> Well, maybe. The docs for |extensions_are()|
> <http://pgtap.org/documentation.html#extensions_are> says:
>
>     If the |:schema| argument is omitted, all extensions will be checked.

Well, it's even more confusing...

"Name of a schema in which to find extensions."

and

"This function tests that all of the extensions in the named schema, or 
that are visible in the search path, are only the extensions that should 
be there."

Extensions definitely do not belong to schemas (it's the other way 
around), so the docs do need to be updated.
