### ISSUE TITLE
make install on 9.0 and older is broken

### ISSUE THREAD

**Issue by decibel** [theory/pgtap#125]
At least as of v0.96.0, if you do make install the pgtap--0.95.0.sql that's generated doesn't have any compatibility patches applied to it.

**Comment by theory** [comment]
Oy vey.

**Comment by decibel** [comment]
Yeah, I'm inclined to just ignore it, but maybe someone will be 
motivated to fix it (or at least comment that they still need this).

**Comment by decibel** [comment]
IIRC the intention is to drop support for < 9.1, so I'm going to close this.
