### ISSUE TITLE
Handle natively partitioned tables

### ISSUE THREAD

**Issue by keithf4** [theory/pgtap#134]
Doing some development work on pg_partman for native partitioning and was confused for a while why some tests were failing. Then realized they only began to fail once I natively partitioned a table. Specifically, I found that `has_table` fails since it is only looking for a relkind of `'r'` in pg_class. Was going to suggest checking for both `r` and `P` (new partitioned relkind), but appears that the `_rexists()` function only accepts a single relkind argument. So either need a whole new `has_` function for partitioned tables, or maybe some way to accept multiple relkinds when checking for existence?
```
keith@keith=# \sf has_table(name, name, text)
CREATE OR REPLACE FUNCTION public.has_table(name, name, text)
 RETURNS text
 LANGUAGE sql
AS $function$
    SELECT ok( _rexists( 'r', $1, $2 ), $3 );
$function$

keith@keith=# \sf _rexists(char, name, name)
CREATE OR REPLACE FUNCTION public._rexists(character, name, name)
 RETURNS boolean
 LANGUAGE sql
AS $function$
    SELECT EXISTS(
        SELECT true
          FROM pg_catalog.pg_namespace n
          JOIN pg_catalog.pg_class c ON n.oid = c.relnamespace
         WHERE c.relkind = $1
           AND n.nspname = $2
           AND c.relname = $3
    );
$function$

```

**Comment by theory** [comment]
I think add `partition_exists()` and friends.

**Comment by keithf4** [comment]
Created the following function for myself in order to be able to keep testing for now. Seems to work. However, maybe `has_partition()` instead to keep consistent with naming?
```
create or replace function has_partition(name, name, text)
returns text
language sql
as $$
SELECT ok(_rexists('P', $1, $2), $3);
$$;

**Comment by theory** [comment]
Yeah, I would expect that to work. I'd just duplicate all these functions, replacing "table" with "partition":

* `has_table()`
* `hasnt_table()`
* `tables_are()`
* `table_owner_is()`

Those are the functions I can see right now that are specific to `relkind r`.

**Comment by decibel** [comment]
Except shouldn't any partition test functions accept the parent table as well? partitions_are() is the most obvious example of why you'd want that, but I don't think any of these functions make sense if they ignore the table that a partition belongs to.

For partition_owner_is(), can partitions even have different owners?

**Comment by theory** [comment]
Well, should `has_table()` and friends work on partitions? Or on foreign tables, for that matter?

I don't know how the new partition stuff works (is there new partition support now?). Can/should a parent table have data in it? I mean the root table, of course (assuming the old inheritance partition scheme). To me, that's not a partition, so the partition test functions should ignore it. But maybe things are different in 10.0?

Maybe we should also have an `is_partitioned()` function for the root table?

**Comment by keithf4** [comment]
FYI, the functions for this should now be looking for a lower case "p" instead of upper case.
```
create or replace function has_partition(name, name, text)
returns text
language sql
as $$
SELECT ok(_rexists('p', $1, $2), $3);
$$;
```

**Comment by theory** [comment]
Where are we on this feature?

**Comment by keithf4** [comment]
I've add the two functions for checking if a child table is a partition to the README for my testing and been using it without issue

https://github.com/keithf4/pg_partman/blob/master/test/README_test.md#partitioning-in-postgresql-10

For native partitioning it's impossible for the parent to have any data, so no need for any testing there. Should probably be a test to see if a table is a parent, though.  So a pair of checks named something like: `is[nt]_partition_parent()`

**Comment by keithf4** [comment]
I would also expect the existing functions (`has_table(), etc) to work on partition tables. They are still technically tables, just with some extra features the new queries can test for.

**Comment by theory** [comment]
If I just copy the materialized-view test to make `partition_owner_is()`, `partitions_are()`, and `has_partition()`, would that be sufficient? If so, is the wording right? `has_partition()` doesn't test that a partition exists, but that a table is partitioned, right?

**Comment by theory** [comment]
Hrm, I'm thinking those ought to be `partitioned_owner_is()`, `partitioneds_are()`, and `has_partitioned()`. Or, no, we just need an `is_partitioned()` for a parent table, and `is_partition()` for a child table, no?

**Comment by keithf4** [comment]
Yes, for `has_partition()` you feed it the parent table of the partition set to see if it exists and is a partitioned table. But, maybe `is[nt]_partitioned()` would be a better name? Since `has_table()` is usually used to check for table existence and should work on partitioned tables as well I think. I'll leave the naming up to you, since I'm fine either way. 

Assuming that `partitions_are()` would take as arguments `(parent_schemaname, parent_tablename, [child_table1, child_table2, etc], desc)`, I think that would work nicely.

**Comment by keithf4** [comment]
Yeah, I think I like `is[nt]_partitioned()` and `is[nt]_partition()` better. Maybe make the latter `is[]_child_partition()` to make the difference in name/function a little clearer? Also possibly have it accept a parent table name to confirm it is the child of a specific parent and not just any child.

**Comment by theory** [comment]
How about:

* `*_table* stuff recognizes partitioned tables
* Add `is[nt]_partitioned()` and `isnt_partitioned()` to test if a table is partitioned or not
* Add `is[nt]_partition_of()` to test that a table is a partition of another table or not (requires the parent table name as a param)
* Add `partitions_are()` to test all the partitions of another table (requires the parent table name as a param, as you describe).

**Comment by keithf4** [comment]
Looks good!

**Comment by theory** [comment]
Hrm. Do you know how to tell which table the parent of a partition table? I've not spotted anything useful in the catalogs, but I must be missing it…

**Comment by theory** [comment]
Ah, found it in [pg_inherits](https://www.postgresql.org/docs/current/static/catalog-pg-inherits.html).

**Comment by decibel** [comment]
Something important to remember: a "child" table can inherit from *multiple* parents. It would be best if everything that accepts `parent` also has an array version.

**Comment by theory** [comment]
Is that true for partitions?

**Comment by decibel** [comment]
Ahh, I didn't realize this was strictly testing the declarative partitioning.

I have a feeling this is going to trip some people up, though hopefully the fact that it's only 10+ will limit that.
