### ISSUE TITLE
pager setting invalid in PG10

### ISSUE THREAD

**Issue by keithf4** [theory/pgtap#135]
Getting the following error when running against the current HEAD of Postgresql 10 as of this posting
```
$ pg_prove test/test-id.sql 
test/test-id.sql .. unrecognized value "" for "pager"
Available values are: on, off, always.
psql: could not set printing parameter "pager"
```
I've searched in the pgtap code and the only instances I can find of setting the pager are in 
```
./test/setup.sql:\pset pager on
./doc/pgtap.mmd:    \pset pager
```
Neither of which seem to actually affect what is being installed (I tried setting them and reinstalling pgtap). Is this something to do with the `pg_prove` script? I checked its source and I don't see where it's setting the pager.

Things still work fine in 9.6, so seems something in 10 is being more strict about what the pager values can be. Just not sure where pgtap is actually doing this.

**Comment by keithf4** [comment]
Hmm... even this isn't working
```
pg_prove -P pager=on -ovf test/test_native/test-id-native.sql
```
But as you can see below, just running the tests directly in psql seems to work fine, so pg_prove seems to be the culprit here. But I can't see where it's setting the pager value.

The error is confusing as well since it seems to indicate there's a problem in the test file itself. I don't call pset in any of my test scripts.
```
keith@keith=# SELECT set_config('search_path','partman, public',false);
   set_config    
-----------------
 partman, public
(1 row)

Time: 0.278 ms
keith@keith=# 
keith@keith=# SELECT plan(100);
  plan  
--------
 1..100
(1 row)

Time: 4.488 ms
keith@keith=# CREATE SCHEMA partman_test;
CREATE SCHEMA
Time: 1.090 ms
keith@keith=# CREATE SCHEMA partman_retention_test;
CREATE SCHEMA
Time: 0.186 ms
keith@keith=# CREATE ROLE partman_basic;
CREATE ROLE
Time: 0.161 ms
keith@keith=# CREATE ROLE partman_revoke;
CREATE ROLE
Time: 0.125 ms
keith@keith=# CREATE ROLE partman_owner;
CREATE ROLE
Time: 0.121 ms
keith@keith=# CREATE UNLOGGED TABLE partman_test.id_taptest_table (
keith(#     col1 bigint 
keith(#     , col2 text not null default 'stuff'
keith(#     , col3 timestamptz DEFAULT now()) PARTITION BY RANGE (col1);
CREATE TABLE
Time: 6.136 ms
keith@keith=# CREATE TABLE partman_test.undo_taptest (LIKE partman_test.id_taptest_table INCLUDING ALL);
CREATE TABLE
Time: 3.007 ms
keith@keith=# GRANT SELECT,INSERT,UPDATE ON partman_test.id_taptest_table TO partman_basic, PUBLIC;
GRANT
Time: 0.371 ms
keith@keith=# GRANT ALL ON partman_test.id_taptest_table TO partman_revoke;
GRANT
Time: 0.202 ms
keith@keith=# 
keith@keith=# SELECT create_parent('partman_test.id_taptest_table', 'col1', 'native', '10', p_jobmon := false, p_start_partition := '3000000000');
 create_parent 
---------------
 t
(1 row)

Time: 79.883 ms
keith@keith=# 
keith@keith=# INSERT INTO partman_test.id_taptest_table (col1) VALUES (generate_series(3000000001,3000000009));
INSERT 0 9
Time: 0.884 ms
keith@keith=# 
keith@keith=# SELECT has_table('partman_test', 'id_taptest_table_p3000000000', 'Check id_taptest_table_p3000000000 exists');
                    has_table                     
--------------------------------------------------
 ok 1 - Check id_taptest_table_p3000000000 exists
(1 row)

Time: 3.058 ms
```

**Comment by theory** [comment]
Looks like it's set [in TAP::Parser::SourceHandler::pgTAP](/theory/tap-parser-sourcehandler-pgtap/blob/master/lib/TAP/Parser/SourceHandler/pgTAP.pm#L312). How does that need to change?

**Comment by keithf4** [comment]
It needs to have an actual value, one of the 3 given in the error. Guessing "on" is the default value. 

https://www.postgresql.org/docs/current/static/app-psql.html

Either that or have the default not have the equal sign without a value. Reading the docs, not giving it a value just toggles it on and off.
```
keith@keith=# \pset pager off
Pager usage is off.
keith@keith=# \pset pager on
Pager is used for long output.
keith@keith=# \pset pager 
Pager usage is off.
keith@keith=# \pset pager 
Pager is used for long output.
keith@keith=# 
```

**Comment by keithf4** [comment]
This seems to have stopped the error... but now pgtap just hangs after printing the number of tests
```
/usr/local/share/perl/5.22.1/TAP/Parser/SourceHandler $ diff pgTAP.pm.orig pgTAP.pm
312c312
<       --pset pager=
---
>       --pset pager=on
```
Now it just stops and hangs at this point. Not sure what else to do now :(
```$ pg_prove -ovf test/test-id.sql 
test/test-id.sql .. 
partman, public
1..119
```

**Comment by theory** [comment]
Set it to off! You don't want the pager.

**Comment by theory** [comment]
Older versions didn't have on/off, only 1 or "". Annoying that the code might have to check. :-(

**Comment by keithf4** [comment]
Gah... that was my mistake. Apparently there was an open transaction in another window and that was blocking a statement in my script. But, I set it to off and things seem to be working now.

Thanks!

**Comment by keithf4** [comment]
Maybe time to start limiting support of pgtap to supported versions of PostgreSQL? Have to make a cutoff at some point to maintain your own sanity, I say. :)

Maybe make the cutoff at 9.0? Looks like on/off is supported back to at least there at a quick glance.

**Comment by decibel** [comment]
Actually, there's other changes queued up that will depend on 9.1 (IIRC 
because 9.1 is what introduced extensions). But before that can happen a 
last version supporting the old stuff needs to go out. I don't remember 
offhand where we're at with that.

**Comment by theory** [comment]
I didn't finish it. Got close, don't remember the holdup. Should just do it. Will try to get to it this week.
