### ISSUE TITLE
Pre-built pgTAP Files

### ISSUE THREAD

**Issue by caramelomartins** [theory/pgtap#138]
Hello,

Hope you are all fine. This is more of a question than an issue.
Would it be possible/interesting to have pre-built SQL files for the current version of pgTAP?

I understand that having this for all PostgreSQL might not be possible at the moment.

**Comment by theory** [comment]
I don't understand the question. But since it's a general inquiry, perhaps it's better sent to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users)?

**Comment by caramelomartins** [comment]
After thinking about it for two seconds I realize it is not a very smart question. In any case, thanks for replying back. :+1:
