### ISSUE TITLE
Packaged on Alpine

### ISSUE THREAD

**Issue by ylavoie** [theory/pgtap#139]
What is the best way to have pgtap packaged on Alpine? It is on Debian/Ubuntu.

**Comment by theory** [comment]
Hi @ylavoie. I'm not sure. I *think* that the [PostgreSQL community Apt repo](https://wiki.postgresql.org/wiki/Apt) includes pgTAP. Have you tried that?

**Comment by ludovicc** [comment]
Hello, I have packaged pgTap in a Docker container using Alpine as base image. It may help, but I have not created an Alpine package here.

**Comment by theory** [comment]
Awesome, @ludovicc, thank you! Care to post an announcement to the [mail list](http://lists.pgfoundry.org/pipermail/pgtap-users/)?

**Comment by ylavoie** [comment]
@theory Apt handles only Debian or Ubuntu, not Alpine which has its own packages.
@ludovicc I did put something up for my own needs on Alpine but haven’t made it into a package.
