### ISSUE TITLE
Automatically set search_path in runtests?

### ISSUE THREAD

**Issue by hgl** [theory/pgtap#141]
Currently it seems `runtests` run all functions with the default search_path.

I wonder if it's possible to automatically set search_path to be prefixed with the schema name that the function is found within before executing it? If not, do you think it makes sense to include such an option?

My use case is that for my test functions, they sometimes implicitly refer to tables/types specified in their own schema.  And there are multiple schemas to be tested. Specifying a static `search_path` before running `pg_prove` won't work, and having to prefix many things with schema names seems tedious.

**Comment by decibel** [comment]
It would need to be optional, but I don't see a problem with adding a parameter to the function.

What I'm not sure of is how difficult it'd be to integrate into pg_prove.

**Comment by theory** [comment]
I deal with this by having my test functions explicitly schema-qualify the dependent objects they need. You can also use [`SET LOCAL`](https://www.postgresql.org/docs/current/static/sql-set.html) at the top of your function to prepend a schema just for the duration of the function call, or use the `SET configuration_parameter ` syntax of [`CREATE FUNCTION`](https://www.postgresql.org/docs/current/static/sql-createfunction.html) to set it for the function at compile time.

**Comment by hgl** [comment]
Thanks. I'll try that.
