### ISSUE TITLE
New release with PG10 support?

### ISSUE THREAD

**Issue by ChristophBerg** [theory/pgtap#142]
Hi,
I can see test issues with PG10 being fixed in master, thanks for that.
Would you consider making a new release with these fixes? That would make it easier for me to update the package for Debian and apt.postgresql.org.
Thanks!

**Comment by theory** [comment]
@decibel: It's time.

**Comment by decibel** [comment]
My recollection was you were going to do this one and document the process?

**Comment by rodo** [comment]
As mention in https://github.com/theory/pgtap/issues/129 could we stop support version 9.1 and older ?

**Comment by theory** [comment]
I'm going to do one last release supporting 8.1 and later, then @decibel is gonna rip out all the older stuff for the next release after that.

**Comment by theory** [comment]
[Done](https://pgxn.org/dist/pgtap/).
