### ISSUE TITLE
Testing functions that SET TRANSACTION ISOLATION LEVEL?

### ISSUE THREAD

**Issue by hgl** [theory/pgtap#144]
I have a function I'd like to test with `runtests`, but the function contains `SET TRANSACTION ISOLATION LEVEL SERIALIZABLE`, and postgresql complains that:

```
ERROR:  SET TRANSACTION ISOLATION LEVEL must be called before any query
```

Is there a way to work around that? I don't think I need serializable isolation while testing, but there doesn't seems to be a way to temporarily disable this statement in the function.

**Comment by theory** [comment]
Alas, no. pgTAP relies on transactions to keep state. Changing that would require a major rewrite — or [autonomous sub transactions](https://wiki.postgresql.org/wiki/Autonomous_subtransactions), perhaps. To deal with this sort of problem, I tend to abstract the transaction-handling stuff into another function that I don't test, or else add some sort of configuration to disable the transactional stuff while running tests.

**Comment by hgl** [comment]
I took your advice and moved transaction-handling stuff out of the function, and I can test without such errors now. Thanks.
