### ISSUE TITLE
results_eq can only test cursor when VALUES is used?

### ISSUE THREAD

**Issue by hgl** [theory/pgtap#145]
After reading the doc, I expect that I can use VALUES statement to compare it with query result, but it doesn't seem to be the case:

```
    RETURN NEXT results_eq(
        'SELECT 1',
        'VALUES(1)',
        'compare'
    );
```
Fails with:

```
ERROR:  cannot open EXECUTE query as cursor
```

Replacing `'VALUES(1)'` with `Array[1]` works.

Is that by design?

I'd like to somehow specify the expected value in a table form (like what the VALUES statement offers) to compare against a query result. Is there a direct way (without creating a temp table, etc, which seems to be tedious)?

**Comment by hgl** [comment]
Another somewhat related quick question:

If the query uses variables defined previously, what's the most elegant way to embed them into the string? I find resorting to `format` to be a bit verbose, not sure if there is a better way.

**Comment by theory** [comment]
You can use `VALUES()`; see the example [in the docs](http://pgtap.org/documentation.html#results_eq). But an array is also supported, and is easier if you just have one column of results.

BTW, I suggest you join the [mail list][(http://pgfoundry.org/mail/?group_id=1000389) to ask questions. Better help there than here in the issues interface.

**Comment by hgl** [comment]
@theory Thanks for pointing me to the mail list. I sent a mail, but it doesn't appear in the archive and I don't get any error response mail. The last mail I can see in the archive is from August.

This is what I sent, I suspect the error I encountered is a bug:

> Hi,
> 
> This is a follow up to https://github.com/theory/pgtap/issues/145
> 
> I have this function in my db:
> 
> CREATE FUNCTION test_foo()
> RETURNS SETOF TEXT LANGUAGE plpgsql AS $$
> BEGIN
>     RETURN NEXT results_eq(
>         'SELECT 1',
>         'VALUES(1)'
>     );
> END$$;
> 
> And when I use pg_prove --run-tests to test it, I get:
> 
> runtests(‘foo'::name, '^test'::text); .. ERROR:  cannot open EXECUTE query as cursor
> CONTEXT:  PL/pgSQL function results_eq(text,text,text) line 8 at OPEN
> PL/pgSQL function test_foo() line 6 at RETURN NEXT
> PL/pgSQL function _runner(text[],text[],text[],text[],text[]) line 62 at FOR over EXECUTE statement
> SQL function "runtests" statement 1
> Dubious, test returned 1 (wstat 256, 0x100)
> No subtests run
> 
> Test Summary Report
> -------------------
> runtests('foo'::name, '^test'::text); (Wstat: 256 Tests: 0 Failed: 0)
>   Non-zero exit status: 1
>   Parse errors: No plan found in TAP output
> Files=1, Tests=0,  0 wallclock secs ( 0.05 usr +  0.05 sys =  0.10 CPU)
> Result: FAIL
> 
> What might be the cause? My pgtap is built from the master branch of the github repo, not sure if it’s related.
> 
> Regards,
> Glen

**Comment by hgl** [comment]
I start to get error reports from my gmail server:

```
The response from the remote server was:
454 4.7.1 <pgtap-users@lists.pgfoundry.org>: Relay access denied
```

Looks like the mail list is down?

**Comment by theory** [comment]
Replied to the email on list, but for posterity, here's the answer:

In short: Your example is too short. pgTAP looks at a string to decide if it’s a cursor name or a query, and the heuristic it relies on is, if the string starts with a double quote or contains no whitespace, it assumes it’s a cursor name. You pass 'SELECT 1', which contains a space, and 'VALUES(1)', which does not. So it thinks 'VALUES(1)' is a cursor. You can fix it just by adding whitespace:

    CREATE OR REPLACE FUNCTION test_foo(
    ) RETURNS SETOF TEXT LANGUAGE plpgsql AS $$
    BEGIN
        RETURN NEXT results_eq(
            'SELECT 1',
            'VALUES (1)'
        );
    END;
    $$;
