### ISSUE TITLE
Installing to 9.6.5 and 9.6.6 creates extension in v 10 directory

### ISSUE THREAD

**Issue by davoscollective** [theory/pgtap#149]
I'm not sure if this commit perhaps fixes this https://github.com/theory/pgtap/commit/a5dd26f41c0b947128687f1c7d64b1349258377b  

or if it's related to this issue https://github.com/theory/pgtap/issues/125

When I make install to pg 9.6.5 or 9.6.6,  then try to run `CREATE EXTENSION pgtap;`

I get this error
```
ERROR:  could not open extension control file "/usr/share/postgresql/9.6/extension/pgtap.control": No such file or directory
STATEMENT:  CREATE EXTENSION pgtap;
```
I see in the installation that it has installed to this directory:
`/usr/share/postgresql/10/extension/pgtap.control`

 I've had a look through the code but not sure how it makes the decision on which directory to install to. 

Here's the end of the installation where I see the directory it installs to:

```
/bin/mkdir -p '/usr/share/postgresql/10/extension'
/bin/mkdir -p '/usr/share/postgresql/10/extension'
/bin/mkdir -p '/usr/share/doc/postgresql-doc-10/extension'
/usr/bin/install -c -m 644 .//pgtap.control '/usr/share/postgresql/10/extension/'
/usr/bin/install -c -m 644 .//sql/pgtap--0.90.0--0.91.0.sql .//sql/pgtap--0.91.0--0.92.0.sql .//sql/pgtap--0.92.0--0.93.0.sql .//sql/pgtap--0.93.0--0.94.0.sql .//sql/pgtap--0.94.0-
-0.95.0.sql .//sql/pgtap--0.95.0--0.96.0.sql .//sql/pgtap--0.96.0--0.97.0.sql .//sql/pgtap--0.97.0--0.98.0.sql .//sql/pgtap--0.98.0.sql .//sql/pgtap--unpackaged--0.91.0.sql .//sql/
pgtap-core--0.98.0.sql .//sql/pgtap-core.sql .//sql/pgtap-schema--0.98.0.sql .//sql/pgtap-schema.sql .//sql/pgtap.sql .//sql/uninstall_pgtap.sql  '/usr/share/postgresql/10/extensio
n/'
/usr/bin/install -c -m 644 .//doc/pgtap.mmd '/usr/share/doc/postgresql-doc-10/extension/'
```

**Comment by davoscollective** [comment]
I've tested using PG v9.6.4 which works fine, so I am sticking with that for now.

**Comment by theory** [comment]
The PGXS Makefile tells it where to put it, and it gets the location of the PGXS Makefile from `pg_config`. Looks like you built against Postgres 10. What's the output of `pg_config --pgxs`? Make sure you have the proper `pg_config` in your path!

**Comment by davoscollective** [comment]
Thanks 
When I run `pg_config --pgxs` 
it tells me
`You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.`

I was running this as part of the build, which must be working with postgres 9.6.4, but doesn't work with 9.6.5 and 9.6.6:
apt-get installl -y postgresql-server-dev-all

I think that must be the problem. Thanks for pointing me in the right direction with pg_config.

**Comment by davoscollective** [comment]
Oh, ignore previous comment i was trying to pull apt package while offline :(

Real output of `pg_config --pgxs`
is this:
`/usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk`

However I am definitely running 9.6.6 because running `SELECT version();` returns this:

```
                                         version
------------------------------------------------------------------------------------------
 PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
```

I think that at this stage the problem is that this `apt-get installl -y postgresql-server-dev-all` is creating that postgres extensions lib under the v10 directory, so I'll switch to using the more specific `apt-get installl -y postgresql-server-dev-9.6`

Again, thanks for pointing me in the right direction. pgTAP can't possibly be expected to install correctly when the extension library isn't in the right place :)
