### ISSUE TITLE
Support for regular table inheritance

### ISSUE THREAD

**Issue by lossendae** [theory/pgtap#152]
Hello,

Native partition are handled by partition functions (#134) but i didn't find how to check for regular table inheritance (relkind 'r').

Is it supported ?

**Comment by theory** [comment]
No. Want to add it?

**Comment by lossendae** [comment]
Hi Theory,

Yes I would but would mind giving me some guidance on how to proceed ? I'm not familiar with the `patch` and the `*.in` files.

Which one are created by hand ? Which one is generated ? Should i provide everything in a PR ? Or only the tests and then you will add the patches and version number ?

**Comment by theory** [comment]
Don't worry about the patch files; they get updated before release. The [pg_class](https://www.postgresql.org/docs/9.1/static/catalog-pg-class.html) `relkind` column doesn't have a letter to represent inheritance ("r" is an ordinary table). There is the `relhassubclass` column, though, so you can tell if a table has children; would be pretty easy to implement a `has_subclass()` function similar to how `has_table()`, but with the additional check that `relhassubclass ` is true. I think you would need to join to [pg-inherits](https://www.postgresql.org/docs/9.1/static/catalog-pg-inherits.html) to determine if a table is a child. The `is_clustered()` function is structured similarly to that.

**Comment by theory** [comment]
Added some inheritance testing functions in fff1a3e.
