### ISSUE TITLE
Tag and release v0.99.0

### ISSUE THREAD

**Issue by 1ma** [theory/pgtap#156]
So we'll be able to update :smiley:

**Comment by decibel** [comment]
I'm going to see if I can pull https://github.com/theory/pgtap/pull/128 in as part of this.

**Comment by ChristophBerg** [comment]
Hi,
this is starting to hurt - all packages using pgtap in their testsuite can't be updated to PG11 on apt.postgresql.org because we don't have a pgtap yet that supports 11.
Please consider releasing :)
Thanks!

**Comment by theory** [comment]
@decibel do we need to find some other folks to help with maintenance and release management? Any volunteers?

**Comment by decibel** [comment]
Quick update: I'm really reluctant to push out 0.99.0 (or dare I say 1.0.0) without #128, and that's currently blocked by #161. #161 actually shows why #128 is so important: it turns out that the 0.97.0->0.98.0 upgrade is broken.

**Comment by decibel** [comment]
@theory, did you write down what the release procedure is? Or were you going to do that this time around.

Also, assuming we drop 8.4 and 9.0 (necessary to pull in #128, which I think we really should do), should we make this 1.0.0?

**Comment by theory** [comment]
Yes, it's in [release.md](/theory/pgtap/blob/master/release.md). I'm fine with 1.0.0.

**Comment by ChristophBerg** [comment]
Can we get 0.99.0 released even if not all upgrade-testing issues are resolved yet? The current state is holding back pg_partman and mimeo from getting upgraded because their tests depend on pgtap, and pgtap is broken with PG10 and 11.

**Comment by wesselvdv** [comment]
@ChristophBerg What's broken about pgtap and pg10? I am using it without issues.

**Comment by theory** [comment]
@ChristophBerg I can try to do a release this week. Meanwhile, would you be interested in helping with pgTAP maintenance — or at least release management? I hate to stand in the way of you shipping your own code.

**Comment by ChristophBerg** [comment]
Hi @theory, I'm not sure I could be of any help with actual development, but I can surely work on releasing and possibly going through the list of open issues and PRs. (This is about what I'm doing with check_postgres.)

**Comment by theory** [comment]
[Done](https://pgxn.org/dist/pgtap/). For the future, @ChristophBerg, if you want to make a release, drop me your PGXN username and I'll add you as co-owner. I'll make you a committer here now. When it comes time to make a release, follow the instructions in [release.md](/theory/pgtap/release.md).

**Comment by theory** [comment]
Found your PGXN ID and made the grant, @ChristophBerg. All set!

**Comment by ChristophBerg** [comment]
Thanks!
