### ISSUE TITLE
pg_prove missing from rpm package?

### ISSUE THREAD

**Issue by Asta1986** [theory/pgtap#157]
Hello, first of all let me say thank you, pgtap is a great project.
I've installed it on a Ubuntu 16.04 system using these packages https://packages.ubuntu.com/xenial/postgresql-9.5-pgtap and everything works well.
On a Fedora system on the other hand, I installed it using this package https://download.postgresql.org/pub/repos/yum/9.5/fedora/fedora-27-x86_64/pgtap95-0.98.0-1.f27.noarch.rpm and although it installs fine pg_prove doesn't seem to be included, so I had to manually build it from source and that didn't work well. I also checked the rpm on that repo for Postgres 10 but it seems to contain the same files.
Best regards.

**Comment by theory** [comment]
Yeah, I don't know why the PostgreSQL Yum repo doesn't have a pg_prove package. You can ask [here](https://yum.postgresql.org/contact.php). It would need to be an RPM for the [TAP-Parser-SourceHandler-pgTAP](http://search.cpan.org/dist/TAP-Parser-SourceHandler-pgTAP) Perl package.

**Comment by Asta1986** [comment]
I opened an issue on the postgres' redmine project and they've added pg_prove to the rpm.
Regards.
