### ISSUE TITLE
Example for runtests() broken in doc? ("What a sweet unit!")

### ISSUE THREAD

**Issue by rngadam** [theory/pgtap#163]
The example given is problematic:

```
CREATE OR REPLACE FUNCTION setup_insert(
) RETURNS SETOF TEXT AS $$
    RETURN NEXT is( MAX(nick), NULL, 'Should have no users') FROM users;
    INSERT INTO users (nick) VALUES ('theory');
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION test_user(
) RETURNS SETOF TEXT AS $$
   SELECT is( nick, 'theory', 'Should have nick') FROM users;
END;
$$ LANGUAGE sql;
```

* missing ```CREATE TABLE IF NOT EXISTS users(nick TEXT);```
* setup_insert plpgsql code is missing BEGIN / END; block
* extraneous ```END;``` in test_user
* missing example of expected output
* should be isolated to testschema as it seems to be poor practice to dump it in public schema

This is the example I would have liked (I can copy paste into my SQL editor and have it run successfully):

```
CREATE TABLE IF NOT EXISTS users(nick TEXT);
CREATE SCHEMA IF NOT EXISTS testschema; 
CREATE OR REPLACE FUNCTION testschema.setup_insert(
) RETURNS SETOF TEXT AS $$
BEGIN
    RETURN NEXT is( MAX(nick), NULL, 'Should have no users') FROM users;
    INSERT INTO users (nick) VALUES ('theory');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION testschema.test_user(
) RETURNS SETOF TEXT AS $$
   SELECT is( nick, 'theory', 'Should have nick') FROM users;
$$ LANGUAGE sql;

SELECT * FROM runtests('testschema'::name);
```

expected output:

```
    # Subtest: public.test_user()
    ok 1 - Should have no users
    ok 2 - Should have nick
    1..2
ok 1 - public.test_user
1..1
```

**Comment by decibel** [comment]
<over_engineering>
@theory, given the current doc build system (which I'm not terribly familiar with), is there a way that examples could be maintained as separate files that could have their own unit tests? I know that asciidoctor (and maybe plain asciidoc) has support for that; I don't think markdown does, though a pre-processor might be an option.

https://blog.golang.org/examples is definitely worth a read in this regard.
</over_engineering>

**Comment by theory** [comment]
I love Go's builtin support for examples in test files. Super nice. Of course, pgTAP isn't written in Go, and just depends on boring build tools. Docs are written in Markdown. There are probably tools we could use or write to:

1. Put examples into test scripts
2. Parse the test scripts for examples
3. Inject them into the relevant sections of the docs
4. Distribute releases with the docs fully-built

If someone wanted to do that work, I'd certainly welcome it! Meanwhile, I'm sure there are many doc issues like the one @rngadam mentions here. I generally don't worry much about completeness of examples — I read a lot of docs in which various other objects are assumed to exist for the purposes of the example, and the `users` table is one such example here. Still, it's a one-liner, so I'm happy to add it and fix the PL/pgSQL bugs.

**Comment by decibel** [comment]
Asciidoctor has support for including files, and IIRC it can actually include output from executables. It's also easy to get it to generate HTML and PDFs. So I think the only part that's missing is moving the examples out into scripts that can actually be tested. That'd be a decent amount of work, but maybe someone's willing to do it. (Or maybe it could be scripted if the formatting of examples is consistent enough.)
