### ISSUE TITLE
Test for `ON DELETE CASCADE`

### ISSUE THREAD

**Issue by dianhenglau** [theory/pgtap#167]
Assume I have the following tables:

    CREATE TABLE person (
        id SERIAL,
        name TEXT NOT NULL,
        PRIMARY KEY (id)
    );

    CREATE TABLE leave (
        id SERIAL,
        taken_by INTEGER NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY (taken_by) REFERENCES person (id)
            ON DELETE CASCADE
    );

I can test the foreign key constraint with `fk_ok`:

    SELECT fk_ok('leave', 'taken_by', 'person', 'id');

Is there a way to test for the `ON DELETE CASCADE`?

I know I can `insert` a `person`, `insert` a `leave` refer to that `person`, `delete` that `person`, and test for existence of that `leave`. Is there a shorter way?

Thank you.

**Comment by theory** [comment]
There is not; I personally do the insert, delete, and check testing you describe.

BTW, questions like this are best asked on the [mail list](https://groups.google.com/forum/#!forum/pgtap-users).

**Comment by dianhenglau** [comment]
Noted. Thank you!
