### ISSUE TITLE
Support row security policies

### ISSUE THREAD

**Issue by rodo** [theory/pgtap#169]
Since the version 9.5 PostgreSQL support row security policies https://www.postgresql.org/docs/9.5/static/ddl-rowsecurity.html these new feature must be present in our best unittest tool
I'll propose some PR soon around this point

**Comment by pau4o** [comment]
@theory @rodo I've started some work to introduce policy tests. You can check my progress at: https://github.com/pau4o/pgtap/pull/1

My work is based on PostgreSQL v9.6

I'll be glad to receive your feedback and guidance.
