### ISSUE TITLE
runtests outputs incorrect TAP format

### ISSUE THREAD

**Issue by lmergner** [theory/pgtap#173]
When I pipe the output from runtests() into [a TAP consumer](https://github.com/python-tap/tappy) it complains about a missing plan (1..N), which runtests prints at the end of the test output. I don't see [any examples of TAP output](https://testanything.org/tap-specification.html) that have the plan printed this way. Am I wrong? 

```
echo "SELECT * FROM runtests('whatever'::name);" | psql -h 192.168.1.68 -p 5432 -U postgres -d pytest-pgtap --no-psqlrc --quiet --no-align --pset pager=off --pset tuples_only=true --set ON_ERROR_STOP=1 | tappy
```
I'm trying to parse the output from pgtap for use with a python test harness. 

![runtests_example](https://user-images.githubusercontent.com/2166105/42795624-1d6dbcc4-893a-11e8-9208-4c3ed0bd3f46.jpeg)

**Comment by theory** [comment]
You need to remove all the extraneous output that `psql` makes. See [TAP::Parser::SourceHandler::pgTAP](/theory/tap-parser-sourcehandler-pgtap/blob/master/lib/TAP/Parser/SourceHandler/pgTAP.pm#L303) for the appropriate options to `psql` to make it output only TAP (modulo error outout).

**Comment by theory** [comment]
Oh, yeah, so you did, sorry. Maybe tappy doesn’t support subtests?
