### ISSUE TITLE
System column changes in PG11

### ISSUE THREAD

**Issue by keithf4** [theory/pgtap#174]
Getting several errors when trying to install on PG11
```
keith@keith=# create extension pgtap;
2018-07-19 17:06:26.793 EDT [10367] ERROR:  column c.relhaspkey does not exist at character 249
2018-07-19 17:06:26.793 EDT [10367] QUERY:  
	    SELECT EXISTS(
	            SELECT true
	              FROM pg_catalog.pg_namespace n
	              JOIN pg_catalog.pg_class c      ON c.relnamespace = n.oid
	              JOIN pg_catalog.pg_constraint x ON c.oid = x.conrelid
	             WHERE c.relhaspkey = true
	               AND n.nspname = $1
	               AND c.relname = $2
	               AND x.contype = $3
	    );
	
2018-07-19 17:06:26.793 EDT [10367] STATEMENT:  create extension pgtap;
ERROR:  column c.relhaspkey does not exist
LINE 7:              WHERE c.relhaspkey = true
                           ^
QUERY:  
    SELECT EXISTS(
            SELECT true
              FROM pg_catalog.pg_namespace n
              JOIN pg_catalog.pg_class c      ON c.relnamespace = n.oid
              JOIN pg_catalog.pg_constraint x ON c.oid = x.conrelid
             WHERE c.relhaspkey = true
               AND n.nspname = $1
               AND c.relname = $2
               AND x.contype = $3
    );

Time: 35.377 ms
```
Checking release notes, the relhaspkey column has been removed from pg_class and recommends checking pg_index instead. https://www.postgresql.org/docs/devel/static/release-11.html
```
Remove relhaspkey column from system table pg_class (Peter Eisentraut)

Applications needing to check for a primary key should consult pg_index.
```

Temporarily cleared that one out to try and allow installation then ran into this one as well
```
keith@keith=# create extension pgtap;
2018-07-19 17:16:58.491 EDT [11420] ERROR:  column p.proisagg does not exist at character 79620
2018-07-19 17:16:58.491 EDT [11420] HINT:  Perhaps you meant to reference the column "p.prolang".
2018-07-19 17:16:58.491 EDT [11420] STATEMENT:  create extension pgtap;
ERROR:  column p.proisagg does not exist
HINT:  Perhaps you meant to reference the column "p.prolang".
```
This column has been replaced with a new one
```
Replace system table pg_proc's proisagg and proiswindow with prokind (Peter Eisentraut)

This new column more clearly identifies functions, procedures, aggregates, and window functions.
```

**Comment by theory** [comment]
How far back does pg_index exist?

**Comment by keithf4** [comment]
7.1
Along with the indisprimary column. So I think you're safe.

https://www.postgresql.org/docs/7.1/static/catalog-pg-index.html

**Comment by theory** [comment]
Does that fix it for yo, @keithf4?

**Comment by theory** [comment]
Oh, I dumbly didn't read far enough to see you were reporting two issues. I'll take a look at the other one soon.

v0.99.0 has not been released, so this will only be an issue for folks who have installed from the repo. They will have to remove and reinstall pgTAP; everyone else can use `ALTER EXTENSION UPDATE`.

**Comment by theory** [comment]
That takes care of the proagg change, @keithf4. Now that it loads, there's a new test failure. I'll get that fixed today.

**Comment by theory** [comment]
All tests pass on 11beta2 as of 4f7bbcf. Give it a try, @keithf4?

**Comment by keithf4** [comment]
So far so good. Thanks!

If the version in this repo is not meant to be the "stable" version, can you please not set the version in pgtap.control to it? Just leave the control file set to what you're considering stable. Then the default version installed from the repo is stable and if anyone wants to install the most recent, unstable, they can run the extension update to it.

**Comment by theory** [comment]
I think what might make sense is to append a prerelease version in the repo, e.g., 0.99.0-dev. Then when v0.99.9 is released you should be golden.

Although then I guess updates won't work. We could just do the patch level, make it 0.98.1 after the release of 0.98.0, and the next release (and the upgrade scripts for it) would be 0.99.0…
