### ISSUE TITLE
[REGRESSION] has_function fails to recognize fully-qualified type names in 0.99 (worked in 0.97)

### ISSUE THREAD

**Issue by strk** [theory/pgtap#179]
Against a PostgreSQL versioned 9.6, pgtap 0.99.0 fails a test that 0.97.0 passes.
The test is:
> SELECT has_function('bde', 'bde_get_app_specific', ARRAY['bde.crs_appellation', 'character']);

The function takes a complex type being a table under the `bde` schema.
For testing, the table and function are defined in http://github.com/linz/linz-bde-schema

**Comment by strk** [comment]
Note that dropping the `bde.` prefix makes the test PASS in 0.99 but fail in 0.97, so I don't know how to write the test in a way that passes independently from the pgtap issue

**Comment by strk** [comment]
The problem seems to be in the tap_funky function:

0.97:
> select args from tap_funky where name = 'bde_get_app_specific' and args like '%appellation%';
>  bde.crs_appellation,character

0.99:
> select args from tap_funky where name = 'bde_get_app_specific' and args like '%appellation%';
> crs_appellation,character

The `args` field of the `tap_funky` view is the same for both versions:
>  array_to_string(p.proargtypes::regtype[], ','::text) AS args,

The session `search_path` is the same for both databases, but WAIT, it includes `$user` which is `bde` in the failing case !

Ok so I think it's not a regression, but a somewhat not-easily predictable usage pattern. Qualification is there only when the argument type is NOT in the search_path!

**Comment by strk** [comment]
I'd say the `has_function` function could re-generate qualification of requested types (or the test could, I guess).

This call resolves in the appropriate way in both situations:
> select 'bde.crs_appellation'::regtype;

So the `_got_func` function could force the ::regtype cast in each passed argument. Maybe taking a `regclass[]` instead of a `text[]` ?

**Comment by strk** [comment]
Note that currently we have `function has_function(unknown, unknown, regtype[]) does not exist`

**Comment by strk** [comment]
Please see 180 for a suggested fix (still fails a test, and doesn't add any new one)

**Comment by theory** [comment]
Fixed ion 3c98e8d.
