### ISSUE TITLE
Prokind column not found in PostgreSQL 9.5

### ISSUE THREAD

**Issue by sirnewton01** [theory/pgtap#183]
I'm trying pgtap out on an older PostgreSQL database. I noticed a problem with the latest from the master branch on GitHub where when I run 'make installcheck' I get a bunch of errors related to the missing column. It seems that this commit introduced the reference to the new PG 11 column.

https://github.com/theory/pgtap/commit/15858e222776b904c2c852ec4cba751182738288

Checkout out the commit before is working much better.

**Comment by sirnewton01** [comment]
Ah, I didn't know about PGXN. I'm quite new to the PG world. I'll try the version there.

I thought I'd raise this since the master version wasn't working for me with PG 9.5.

**Comment by theory** [comment]
Yeah, it absolutely should, since the [tests pass](https://travis-ci.org/theory/pgtap) on 8.4-10.

**Comment by sirnewton01** [comment]
I couldn't seem to find a way to download an official release of pgtap from PGXN. Maybe I'm missing something or going partially blind. :)

**Comment by theory** [comment]
The download link is on the [distribution page](https://pgxn.org/dist/pgtap/) (up one in the breadcrumb for the previous link). It looks like this:

<img width="494" alt="screen shot 2018-11-01 at 21 33 30" src="https://user-images.githubusercontent.com/46604/47889001-fd4e8700-de1d-11e8-8202-19fe3f2965c9.png">

You might also want to try the [pgxn client](/pgxn/pgxnclient).

**Comment by sirnewton01** [comment]
Thank you, it's working fine so far with the latest official release on pgxn.
