### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by dribeiroexpertise** [theory/pgtap#186]
Makefile:68: /usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target '/usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

running postgres 9.5.14 on ubunty 16

**Comment by theory** [comment]
Do you have the Postgres development package installed?
