### ISSUE TITLE
pg_prove command not found

### ISSUE THREAD

**Issue by Jackclarify** [theory/pgtap#187]
Environment:
mac: 10.13.6
postgres: 10.5
pgTAP: 0.99.0
TAP-Parse-SourceHandler-pgTAP-3.34.tar.gz

Operations:
curl -Lo pgtap.zip https://api.pgxn.org/dist/pgtap/0.99.0/pgtap-0.99.0.zip
unzip pgtap.zip
cd pgtap-0.99.0
make
make install
make installcheck PGUSER=postgres

Enter into a database:
CREATE EXTENSION IF NOT EXISTS pgtap;

Install pg_prove
cpan App::cpanminus
sudo cpan TAP::Parser::SourceHandler::pgTAP

References: [unit-testing-postgres-with-pgtap](https://medium.com/engineering-on-the-incline/unit-testing-postgres-with-pgtap-af09ec42795), [pgtap](https://pgxn.org/dist/pgtap/doc/pgtap.html)

Restart database, run pg_prove -U postgres sql/a.sql
command not found: pg_prove
What's the matter? Where could I run the pg_prove command? I want to get the test summery by running .sql file with pg_prove. Any help is appreciated, thanks!!! @theory

**Comment by theory** [comment]
What was the output from `sudo cpan TAP::Parser::SourceHandler::pgTAP`? Also, what does this output?

```
perldoc -l TAP::Parser::SourceHandler::pgTAP
perl -E 'say for @INC'
```

**Comment by Jackclarify** [comment]
Hi @theory, thank you for your reply.  Here is the output of those command:
➜  Desktop cpan App::cpanminus
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/Users/leaf/.cpan/Metadata'
  Database was generated on Thu, 13 Dec 2018 00:54:08 GMT
App::cpanminus is up to date (1.7044).
➜  Desktop sudo cpan TAP::Parser::SourceHandler::pgTAP
Password:
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/Users/leaf/.cpan/Metadata'
  Database was generated on Thu, 13 Dec 2018 00:54:08 GMT
TAP::Parser::SourceHandler::pgTAP is up to date (3.34).
➜  Desktop perldoc -l TAP::Parser::SourceHandler::pgTAP
/usr/local/Cellar/perl/5.26.2/lib/perl5/site_perl/5.26.2/TAP/Parser/SourceHandler/pgTAP.pm
➜  Desktop perl -E 'say for @INC'
/usr/local/Cellar/perl/5.26.2/lib/perl5/site_perl/5.26.2/darwin-thread-multi-2level
/usr/local/Cellar/perl/5.26.2/lib/perl5/site_perl/5.26.2
/usr/local/Cellar/perl/5.26.2/lib/perl5/5.26.2/darwin-thread-multi-2level
/usr/local/Cellar/perl/5.26.2/lib/perl5/5.26.2
/usr/local/lib/perl5/site_perl/5.26.2/darwin-thread-multi-2level
/usr/local/lib/perl5/site_perl/5.26.2
Any information will be given if needed. Thanks, --jack

**Comment by Jackclarify** [comment]
Hi @theory , great thanks, it works!
➜  Desktop find /usr/local -name pg_prove
/usr/local/Cellar/perl/5.26.2/bin/pg_prove
➜  Desktop ln -s /usr/local/Cellar/perl/5.26.2/bin/pg_prove /usr/loal/bin
ln: /usr/loal/bin: No such file or directory
➜  Desktop ln -s /usr/local/Cellar/perl/5.26.2/bin/pg_prove /usr/local/bin
➜  Desktop pg_prove --help
Usage:
      pg_prove tests/
      pg_prove --dbname template1 test*.sql
      pg_prove -d testdb --runtests

Options:
     -b   --psql-bin PSQL        Location of the psql client.
     -d,  --dbname DBNAME        Database to which to connect.
     -U,  --username USERNAME    User with which to connect.
     -h,  --host HOST            Host to which to connect.
     -p,  --port PORT            Port to which to connect.
     -P,  --pset OPTION=VALUE    Set psql key/value printing option.
     -S,  --set VAR=VALUE        Set variables for psql session.
     -R   --runtests             Run xUnit test using runtests().
     -s,  --schema SCHEMA        Schema in which to find xUnit tests.
     -x,  --match REGEX          Regular expression to find xUnit tests.

          --ext                  Set the extension for tests (default .pg)
     -r,  --recurse              Recursively descend into directories.
          --ignore-exit          Ignore exit status from test scripts.
          --trap                 Trap Ctrl-C and print summary on interrupt.
          --harness              Define test harness to use.
     -j,  --jobs N               Run N test jobs in parallel (try 9.)
          --rc RCFILE            Process options from rcfile
          --norc                 Don't process default .proverc
          --state OPTION=VALUE   Set persistent state options.

     -v,  --verbose              Print all test lines.
     -f,  --failures             Show failed tests.
     -o,  --comments             Show comments and diagnostics.
          --directives           Only show results with TODO or SKIP directives.
     -q,  --quiet                Suppress some test output while running tests.
     -Q,  --QUIET                Only print summary results.
          --parse                Show full list of TAP parse errors, if any.
          --normalize            Normalize TAP output in verbose output
     -D   --dry                  Dry run. Show test that would have run.
          --merge                Merge test scripts' STDERR and STDOUT.
     -t   --timer                Print elapsed time after each test.
     -c,  --color                Colored test output (default).
          --nocolor              Do not color test output.
          --shuffle              Run the tests in random order.
          --reverse              Run the tests in reverse order.
     -a,  --archive FILENAME     Store the resulting TAP in an archive file.
          --formatter            Result formatter to use.
          --count                Show X/Y test count when not verbose (default)
          --nocount              Disable the X/Y test count.

     -H,  --help                 Print a usage statement and exit.
     -?,                         Print a usage statement and exit.
     -m,  --man                  Print the complete documentation and exit.
     -V,  --version              Print the version number and exit.

THANK YOU @theory 👍

**Comment by pbastia** [comment]
@Jackclarify I ran into the same thing, and found that a simpler step is to relink perl after installing pgtap (instead of manually creating the pg_prove symlink):
```bash
brew unlink perl && brew link perl
```

Environment:
mac: 10.15.7
postgres: 12.6
pgTAP: 1.1.0
