### ISSUE TITLE
ERROR:  type "_time_trial_type" already exists

### ISSUE THREAD

**Issue by strk** [theory/pgtap#189]
Loading pgtap.sql twice in a database errors out with:
> ERROR:  type "_time_trial_type" already exists

It would be nice if there was an idempotent way to install pgtap.
See also #188 for why this is a bigger problem than it could be (cannot upgrade)

**Comment by theory** [comment]
Are you not using `CREATE EXTENSION` and `DROP EXTENSION`?

**Comment by strk** [comment]
> Are you not using `CREATE EXTENSION` and `DROP EXTENSION`?

No, because Amazon RDS service doesn't support it

**Comment by theory** [comment]
Oh, RDS. What Postgres are you using to `make` the extension?

**Comment by theory** [comment]
None. None of the upgrade scripts currently change any types, so is hasn't been an issue. At any rate, `pgtap.sql` is not idempotent; what drives the need to load it twice?

**Comment by strk** [comment]
On Wed, Dec 19, 2018 at 06:10:58PM -0800, David E. Wheeler wrote:
> None. None of the upgrade scripts currently change any types, so is hasn't been an issue. At any rate, `pgtap.sql` is not idempotent; what drives the need to load it twice?

The broken uninstall did (see other ticket).
Maybe add a note in the README about ways to upgrade ?
(uninstall and re-install being it)

**Comment by theory** [comment]
It sounds like #188 was the real issue here. Happy to consider pull requests for an updated README, though. Thanks!
