### ISSUE TITLE
Can we install pgtap on win10 and test SQL against a postgres instance?

### ISSUE THREAD

**Issue by Jackclarify** [theory/pgtap#192]
Hi @theory , can we install pgtap on win10 and test  sql against a postgres instance?

I've seen a answer you have provided several years ago, when I try it on my desptop, it failed.
[How to install pgTAP on Windows?](https://stackoverflow.com/questions/17986606/how-to-install-pgtap-on-windows)

```
copy sql/pgtap.sql.in sql/pgtap.sql
perl.exe -pi.bak -e "s/TAPSCHEMA/tap/g" sql/pgtap.sql
perl.exe -pi.bak -e "s/__OS__/win32/g" sql/pgtap.sql
perl.exe -pi.bak -e "s/__VERSION__/0.24/g" sql/pgtap.sql
perl.exe -pi.bak -e "s/^-- ## //g" sql/pgtap.sql
copy sql/pgtap.sql "%ProgramFiles%\PostgreSQL\9.2\share" 
```

I've installed postgres at C:\Program Files\PostgreSQL\10,
and copy pgtap.sql to C:\Program Files\PostgreSQL\10\share.
when I enter into the database, run command: `CREATE EXTENSION IF NOT EXISTS pgtap;`,
it throw error: `ERROR:  could not open extension control file "C:/Program Files/PostgreSQL/10/share/extension/pgtap.control": No such file or directory`

Any suggestion will be appreciated, thank you!

**Comment by Jackclarify** [comment]
And when I run it with mingw64:
```
Stone@DESKTOP-LIHENSE MINGW64 /c/PROGRA~1/POSTGR~1/10/bin/pgtap-0.99.0
$ env PG_CONFIG="C:/PROGRA~1/POSTGR~1/10/bin/pg_config" make                     
Makefile:68: C:/PROGRA~1/POSTGR~1/10/lib/pgxs/src/makefiles/pgxs.mk: No such fil e or directory                                                                   make: *** No rule to make target 'C:/PROGRA~1/POSTGR~1/10/lib/pgxs/src/makefiles /pgxs.mk'.  Stop.
--
```
And I searched, but many answer are about linux. 
```
sudo apt-get install postgresql-server-dev-all
sudo apt-get install postgresql-common 
```
Could you please give me any prompt?

**Comment by theory** [comment]
Would be helpful to update that [SO answer](https://stackoverflow.com/a/20103602/79202) to use the windows equivalent of 

Could some Windows command expert quickly tell me how to do the equivalent of

    $(pg_config --sharedir)/extension

instead of

    "%ProgramFiles%\PostgreSQL\9.2\share”

Anyone got the chops for that?

**Comment by Jackclarify** [comment]
Hi @theory , I've tried to copy the pgtap.sql and pgtap.control to the folder  "C:/Program Files/PostgreSQL/10/share/extension/", but it still throw error as below.
```
hospital=# create extension pgtap;
ERROR:  extension "pgtap" has no installation script nor update path for version "0.99.1"
```
I will use docker to try again, but it's still appreciated to have a method to install it on windows directly. : ) thanks --Jack

**Comment by theory** [comment]
What is in `C:/Program Files/PostgreSQL/10/share/extension/`? You need the `pgtap--0.99.1.sql` file, too.

There is no Windows installer because PostgreSQL doesn't include Windows support in PGXS, it's extension makefile stuff. But maybe it would work if you had `gmake` installed?

**Comment by jonnyforestGIS** [comment]
Hi guys I was able to install on Windows 10 with PG11 here are my procedures:

1. Use https://strawberryperl.com/
2. git clone https://github.com/theory/pgtap.git
3. Run portable_shell.bat from strawaberryperl an did the following steps:

```cmd

cd pgtapFolder
copy sql/pgtap.sql.in sql\pgtap.sql
perl.exe -pi.bak -e "s/TAPSCHEMA/tap/g" sql\pgtap.sql
perl.exe -pi.bak -e "s/__OS__/win32/g" sql\pgtap.sql
perl.exe -pi.bak -e "s/__VERSION__/0.24/g" sql\pgtap.sql
perl.exe -pi.bak -e "s/^-- ## //g" sql\pgtap.sql
copy sql\pgtap.sql "%ProgramFiles%\PostgreSQL\11\share\extensions"
copy contribut\pgtap.spec  "%ProgramFiles%\PostgreSQL\11\contribut"
copy pgtap.control "%ProgramFiles%\PostgreSQL\11\share\extensions"
ren "%ProgramFiles%\PostgreSQL\10\share\extensions\pgtap.sql" "%ProgramFiles%\PostgreSQL\11\share\extensions\pgtap--1.1.0.sql"

```

After this, I was able to install using PgAdmin4.

I think this can be polished but for now I as able to run it.

**Comment by ericpyle** [comment]
My steps were a little different:

1. Go to https://strawberryperl.com/releases.html and click on the Portable 64bit download link then extract to {strawberryperl} folder
![image](https://user-images.githubusercontent.com/1125565/140190878-5d23c9d5-7d6d-4c49-9ede-09833813845e.png)

2. git clone https://github.com/theory/pgtap.git into {pgtapFolder}
3. Run cmd.exe as Admininstrator (this is so you can copy into ProgramFiles)
4. cd to the extracted portable {strawberryperl} (see step 1) folder and run "portableshell.bat"
5. Then, do the following steps:

```
cd {pgtapFolder}
copy sql\pgtap.sql.in sql\pgtap.sql
perl.exe -pi.bak -e "s/TAPSCHEMA/tap/g" sql\pgtap.sql
perl.exe -pi.bak -e "s/__OS__/win32/g" sql\pgtap.sql
perl.exe -pi.bak -e "s/__VERSION__/0.24/g" sql\pgtap.sql
perl.exe -pi.bak -e "s/^-- ## //g" sql\pgtap.sql
copy sql\pgtap.sql "%ProgramFiles%\PostgreSQL\12\share\extension"
copy contrib\pgtap.spec  "%ProgramFiles%\PostgreSQL\12\contrib"
copy pgtap.control "%ProgramFiles%\PostgreSQL\12\share\extension"
cd "%ProgramFiles%\PostgreSQL\12\share\extension\"
ren "pgtap.sql" "pgtap--1.2.0.sql"
```

**Comment by andhan-ar** [comment]
thx for ericpyle, your step work for me on windows OS

**Comment by michelle0809** [comment]
Hi,
When I execute 'perl.exe -pi.bak -e "s/TAPSCHEMA/tap/g" sql\pgtap.sql', I encountered an error indicating that the locale is not supported.
![image](https://github.com/theory/pgtap/assets/71964831/1f9f2d61-d975-420c-860d-5017be5a8078)

Does it means that pgTAP restricts the database locale? How can I slove this error?

**Comment by theory** [comment]
@michelle0809 let's discuss your issue in #327. I added a comment there about the need to compile the shared library added in v1.3.1.

**Comment by SANJAY943** [comment]
> My steps were a little different:
> 
> 1. Go to https://strawberryperl.com/releases.html and click on the Portable 64bit download link then extract to {strawberryperl} folder
>    ![image](https://user-images.githubusercontent.com/1125565/140190878-5d23c9d5-7d6d-4c49-9ede-09833813845e.png)
> 2. git clone https://github.com/theory/pgtap.git into {pgtapFolder}
> 3. Run cmd.exe as Admininstrator (this is so you can copy into ProgramFiles)
> 4. cd to the extracted portable {strawberryperl} (see step 1) folder and run "portableshell.bat"
> 5. Then, do the following steps:
> 
> ```
> cd {pgtapFolder}
> copy sql\pgtap.sql.in sql\pgtap.sql
> perl.exe -pi.bak -e "s/TAPSCHEMA/tap/g" sql\pgtap.sql
> perl.exe -pi.bak -e "s/__OS__/win32/g" sql\pgtap.sql
> perl.exe -pi.bak -e "s/__VERSION__/0.24/g" sql\pgtap.sql
> perl.exe -pi.bak -e "s/^-- ## //g" sql\pgtap.sql
> copy sql\pgtap.sql "%ProgramFiles%\PostgreSQL\12\share\extension"
> copy contrib\pgtap.spec  "%ProgramFiles%\PostgreSQL\12\contrib"
> copy pgtap.control "%ProgramFiles%\PostgreSQL\12\share\extension"
> cd "%ProgramFiles%\PostgreSQL\12\share\extension\"
> ren "pgtap.sql" "pgtap--1.2.0.sql"
> ```
> 
> If after trying to CREATE the extension you get an error like "error: extension "pgtap" has no installation script nor update path for version "{version}", then change the last step above to `ren "pgtap.sql" "pgtap--{version}.sql"`

**Comment by SANJAY943** [comment]
> My steps were a little different:
> 
> 1. Go to https://strawberryperl.com/releases.html and click on the Portable 64bit download link then extract to {strawberryperl} folder
>    ![image](https://user-images.githubusercontent.com/1125565/140190878-5d23c9d5-7d6d-4c49-9ede-09833813845e.png)
> 2. git clone https://github.com/theory/pgtap.git into {pgtapFolder}
> 3. Run cmd.exe as Admininstrator (this is so you can copy into ProgramFiles)
> 4. cd to the extracted portable {strawberryperl} (see step 1) folder and run "portableshell.bat"
> 5. Then, do the following steps:
> 
> ```
> cd {pgtapFolder}
> copy sql\pgtap.sql.in sql\pgtap.sql
> perl.exe -pi.bak -e "s/TAPSCHEMA/tap/g" sql\pgtap.sql
> perl.exe -pi.bak -e "s/__OS__/win32/g" sql\pgtap.sql
> perl.exe -pi.bak -e "s/__VERSION__/0.24/g" sql\pgtap.sql
> perl.exe -pi.bak -e "s/^-- ## //g" sql\pgtap.sql
> copy sql\pgtap.sql "%ProgramFiles%\PostgreSQL\12\share\extension"
> copy contrib\pgtap.spec  "%ProgramFiles%\PostgreSQL\12\contrib"
> copy pgtap.control "%ProgramFiles%\PostgreSQL\12\share\extension"
> cd "%ProgramFiles%\PostgreSQL\12\share\extension\"
> ren "pgtap.sql" "pgtap--1.2.0.sql"
> ```
> 
> If after trying to CREATE the extension you get an error like "error: extension "pgtap" has no installation script nor update path for version "{version}", then change the last step above to `ren "pgtap.sql" "pgtap--{version}.sql"`

Hi @Eric ,
when i am running "perl.exe -pi.bak -e "s/__OS__/win32/g" sql\pgtap.sql" command facing the below error
"Can't rename C:\pgtap-1.3.1\pgtap-1.3.1\sql\pgtap.sql to C:\pgtap-1.3.1\pgtap-1.3.1\sql\pgtap.sql.bak: Permission denied, skipping file, <> line 11400.".
could you suggest please how i can resolve it.?
