### ISSUE TITLE
invalid type name ""

### ISSUE THREAD

**Issue by strk** [theory/pgtap#193]
I'm getting this error when running `pg_prove` against a database which was loaded `pgtap.sql`:

> invalid type name ""
> CONTEXT:  PL/pgSQL function _funkargs(name[]) line 3 at RETURN
> SQL function "_got_func" statement 1

Note that the `pg_prove` command and the `pgtap.sql` script are probably from different versions, but I'm not sure it matters.

This is happening on Travis-CI, where pgtap is being built and shows patches being applied for PostgreSQL up to 10:

```
patching file sql/pgtap-static.sql
sed -e 's,sql/pgtap,sql/pgtap-static,g' compat/install-10.patch | patch -p0
patching file sql/pgtap-static.sql
sed -e 's,sql/pgtap,sql/pgtap-static,g' compat/install-9.6.patch | patch -p0
patching file sql/pgtap-static.sql
sed -e 's,sql/pgtap,sql/pgtap-static,g' compat/install-9.4.patch | patch -p0
patching file sql/pgtap-static.sql
sed -e 's,sql/pgtap,sql/pgtap-static,g' compat/install-9.2.patch | patch -p0
patching file sql/pgtap-static.sql
sed -e 's,sql/pgtap,sql/pgtap-static,g' compat/install-9.1.patch | patch -p0
patching file sql/pgtap-static.sql
sed -e 's,sql/pgtap,sql/pgtap-static,g' compat/install-9.0.patch | patch -p0
patching file sql/pgtap-static.sql
sed -e 's,sql/pgtap,sql/pgtap-static,g' compat/install-8.4.patch | patch -p0
patching file sql/pgtap-static.sql
sed -e 's,sql/pgtap,sql/pgtap-static,g' compat/install-8.3.patch | patch -p0
```

Database version is 9.6, so it could be a bogus build.

**Comment by strk** [comment]
Note this happens with current master: 32d3748d932d552903fc246b0ada10bec60a1b9e

**Comment by strk** [comment]
On the same 9.6.11 database, version 267081f works fine, and 32d3748 is also bogus against database 9.6.11 so the bug has been introduced in pgtap, it is a regression

**Comment by strk** [comment]
According to git-bisect the culprit seems to be 32d3748d932d552903fc246b0ada10bec60a1b9e itself

**Comment by strk** [comment]
Sorry, I was wrong about the bisect, I'm running it again. Testing requires that a function exists

**Comment by strk** [comment]
Effective test: 

> SELECT no_plan(); SELECT has_function('pg_catalog', 'version', ARRAY['']);

**Comment by strk** [comment]
Here, this time the bisecting is correct:

```
256f12f335522a7c1e2e06ee3a90f213bdaeeff0 is the first bad commit
commit 256f12f335522a7c1e2e06ee3a90f213bdaeeff0
Author: David E. Wheeler <david.wheeler@iovation.com>
Date:   Tue Nov 20 10:20:54 2018 -0500

    Simpler fix for qualified function args.
    
    Just cast the array to `regtype[]`, same as the `tap_funky` view does. Also,
    remove references to a "complex" type in the tests, which is a red herring.
    The issue is schema qualification. So use a simple domain instead of a table.
    Also, fix the test plan.

:040000 040000 55f6264d8bb61c57d09d94757a0a37c1c0cb9830 eaf94ad8f0a16fe7be96da6331c94ff292dfc16a M sql
:040000 040000 010a14c96088be463409597d8158f9ba4ac3b977 a25ba4e8cebc0f910de9c4b5ea5bcc18e7ad7412 M test
```

**Comment by strk** [comment]
@theory it looks like 256f12f335522a7c1e2e06ee3a90f213bdaeeff0 was yours, can you look at this ?
You have the testcase above to put in the automated testsuite

**Comment by strk** [comment]
I put the test in a testcase in #195

**Comment by strk** [comment]
You can see the problem here: https://travis-ci.org/theory/pgtap/jobs/477879305#L1570

**Comment by theory** [comment]
That's not an empty array in #195. If you want an empty array, you have to use `'{}`::text[]`.

**Comment by strk** [comment]
> That's not an empty array in #195. If you want an empty array, you have to use `'{}`::text[]`.

You're right. I'm just pointing out it is a change in behaviour
(it used to work) -- maybe worth noticing it in the CHANGELOG ?

**Comment by theory** [comment]
It worked in b281cfb, which has never been released, so it doesn't make sense to record it in changes.
