### ISSUE TITLE
How to return non-zero exit code with runtests

### ISSUE THREAD

**Issue by steve-chavez** [theory/pgtap#198]
Hello. I have a test suite that I want to run against a CI. I'm using the [runtests](https://pgtap.org/documentation.html#runtests) function.

When I do this:
```bash
psql -v ON_ERROR_STOP=1 -v ON_ERROR_ROLLBACK=1 mydb \
-c "select * from runtests('tests', 'tests$');"

## ...
## I get a normal output with a "not ok" result
## ...

echo $?
```

I always get a 0 exit code. How can I get a non-zero exit code?

**Comment by steve-chavez** [comment]
Just found https://github.com/theory/pgtap/issues/39. That was some time ago. Wonder if there's a workaround available now.

**Comment by steve-chavez** [comment]
Seems [pg_prove](https://pgtap.org/pg_prove.html) is the answer. I mainly went the `runtests` route because of the nicely formatted output.

pg_prove has a nicer format and it returns a non-zero exit code.

For the record, I managed to make pg_prove work with:
```bash
## Works with runtests
PGOPTIONS='--search_path=core,public' pg_prove -d mydb -s tests -x "tests$" --runtests

## Works with regular tests
pg_prove -v -d mydb tests/*
```

Thanks. Closing.

**Comment by cbandy** [comment]
I haven't tried with `runtests()`, but with `finish()` and `ON_ERROR_STOP=1` I use:

```sql
DO $$ BEGIN ASSERT num_failed() = 0; END $$;
```

**Comment by steve-chavez** [comment]
@cbandy Thank you! That's a simpler method than using pg_prove!

@theory I can't find `num_failed()` in the docs, perhaps it should be included?

**Comment by theory** [comment]
It should not be necessary; if you don't want to use [pg_prove](theory/tap-parser-sourcehandler-pgtap/blob/develop/bin/pg_prove), here's how it calls `psql`:

```
psql --dbname mydb \
      --no-psqlrc \
      --no-align \
      --quiet \
      --pset pager=off \
      --pset tuples_only=true \
      --set ON_ERROR_STOP=1 \
      --command "select * from runtests('tests', 'tests$');"
```
