### ISSUE TITLE
1.0.0: Unable to pg_upgrade to Postgres 11

### ISSUE THREAD

**Issue by nasbyj** [theory/pgtap#201]
Attempting to upgrade to version 11 results in this error (in pg_upgrade_dump_*.log):

```
pg_restore: creating VIEW "public.tap_funky"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 199; 1259 16647 VIEW tap_funky nasbyj
pg_restore: [archiver (db)] could not execute query: ERROR:  column p.proisagg does not exist
LINE 26:     "p"."proisagg" AS "is_agg",
             ^
HINT:  Perhaps you meant to reference the column "p.prolang".
```

The issue is that instead of `pg_upgrade` (or possibly pg_dump/restore) doing a simple `CREATE EXTENSION pgtap`; instead it is creating each object in pgtap, and then doing `ALTER EXTENSION "pgtap" ADD ...`.

I'm not sure why `pg_upgrade` is going this route, but until we can get that resolved I think we'll need to remove `"is_agg"` from the `tap_funky` view and create a function that provides that information. A hard-coded function would still fail if you tried to run it, but since function definitions normally are not checked during function creation, that should be OK.

**Comment by nasbyj** [comment]
Turns out `pg_upgrade` needs to control the OIDs assigned to certain objects, like data types, because many catalog tables (such as `pg_attribute`) refer to other catalog table by OID. [This mailing list post](https://www.postgresql.org/message-id/AANLkTimm1c64=xkdpz5ji7Q-rH69zd3cMewmRpkH0WSf@mail.gmail.com) is the decision for `pg_dump --binary-upgrade` to dump individual extension objects.

**Comment by nasbyj** [comment]
I've [reported this to the community](https://www.postgresql.org/message-id/flat/052C3470-917A-4DC5-91B4-81F2D7C8950D%40amazon.com).

**Comment by theory** [comment]
So is this something we need to follow up on here, @nasbyj? This is the same issue as #197, more or less, yes?

**Comment by nasbyj** [comment]
It's similar to #197, but I don't think it's quite the same. #197 appears to simply be something that could be handled in compat/install-10.patch, but that won't work for this pg_upgrade issue.

**Comment by decibel** [comment]
I think the only way to fix this is either to strip prokind from the tap_funky view and fix the _agg functions (making them dynamic), or change tap_funky to refer to an SRF that is version-aware. My plan is to do #207
