### ISSUE TITLE
Travis broken for < 9.4

### ISSUE THREAD

**Issue by nasbyj** [theory/pgtap#212]
Travis no longer passes for master. https://travis-ci.org/theory/pgtap/builds/496774630 shows as clean, but that’s from 7 months ago. https://travis-ci.org/nasbyj/pgtap/builds/591752270 is a straight branch right off of master and it’s broken.

The bottom of https://travis-ci.org/nasbyj/pgtap/jobs/592145045 shows the contents of the extensions directory, which is definitely missing all extensions other than pgTap and plpgsql.

I see two options:

1. Simply stop testing extension test functions in < 9.4. Note that 8.4 and 9.0 are broken for other reasons, so this wouldn't fix those versions.
2. Formally drop support for < 9.4.

Given that 9.4 will be EOL this year, I'm inclined to go with option 2.

**Comment by theory** [comment]
Do we need to install another package that includes contrib extensions?

**Comment by decibel** [comment]
Looks like github didn't like my email reply...

Maybe https://packages.debian.org/jessie/postgresql-contrib-9.4 is the explanation for this? Though if that was really the case then why isn't 9.4 broken?

BTW, I'm getting ready to merge #128, which moves the [Travis test script into our repository](https://github.com/theory/pgtap/pull/128/files#diff-050a988f5d4262b25bfc40e7b9ee006bR1). So if we need to pull in additional packages or something we can do that.

Do you have a linux environment similar to Travis available @theory? (I don't). Can you take a look at the contrib issue?

**Comment by decibel** [comment]
Oh, I just realized that #128 has [code to disable the extensions test if any extensions are not available](https://github.com/theory/pgtap/pull/128/files#diff-b67911656ef5d18c4ae36cb6741b7965R129). (I should really add a WARNING when that happens...) Maybe we can go with that? I'm still not keen on having stuff that's officially supported but doesn't have automated testing though...

**Comment by theory** [comment]
No, I don't. I guess if I was doing this again, I'd try to use the community Apt repos instead. Or find some way to spin up docker images and use those, instead.

**Comment by theory** [comment]
Okay, looks like Travis updated their build images, and the Postgres Apt repo doesn't have older versions of Postgres for some versions of Ubuntu. [For Xenial](http://apt.postgresql.org/pub/repos/apt/dists/xenial-pgdg/), for example, there is no version prior to 9.1. The way to address this, I think, it to instead use a Docker image for each version. I might play around with that a bit next week in some of my other, simpler extensions, and maybe we can adapt it here.

**Comment by nasbyj** [comment]
It looks like going the Docker route would also make it easy to run the travis tests locally, which would be a huge win.

**Comment by theory** [comment]
Yeah, but the official [Postgres image](https://hub.docker.com/_/postgres) only goes back to 9.4, too. :-(

**Comment by cbandy** [comment]
There are old tags, too. https://hub.docker.com/_/postgres?tab=tags&page=12

**Comment by theory** [comment]
Travis stuff replaced with GitHub workflows in 2ccda7f.
