### ISSUE TITLE
Error on usr/share/perl/5.26/App/Prove.pm

### ISSUE THREAD

**Issue by prakashupes** [theory/pgtap#232]
sh ./tools/testers/pg_prove_tests.sh 
```
RELEASE_TYPE b

cd ./tools/testers/
psql -f setup_db.sql
OK
PANIC: could not determine iterator for input  at /usr/share/perl/5.26/App/Prove.pm line 546.
```

**Comment by theory** [comment]
I'm sorry, I can't tell what you're trying to do here. Is `/tools/testers/pg_prove_tests.sh` responsible for the output there? What's in that script?
