### ISSUE TITLE
error: invalid zip file with overlapped components (possible zip bomb)

### ISSUE THREAD

**Issue by xenoterracide** [theory/pgtap#237]
this is on alpine in a dockerfile
https://github.com/xenoterracide/postgis-pgtap/runs/537908437?check_suite_focus=true#step:3:141
```
   inflating: pgtap-1.1.0/sql/pgtap--0.94.0--0.95.0.sql  
  inflating: pgtap-1.1.0/sql/pgtap--0.95.0--0.96.0.sql.in  
  inflating: pgtap-1.1.0/sql/pgtap--0.96.0--0.97.0.sql.in  
  inflating: pgtap-1.1.0/sql/pgtap--0.97.0--0.98.0.sql.in  
  inflating: pgtap-1.1.0/sql/pgtap--0.98.0--0.99.0.sql.in  
  inflating: pgtap-1.1.0/sql/pgtap--0.99.0--1.0.0.sql.in  
  inflating: pgtap-1.1.0/sql/pgtap--1.0.0--1.1.0.sql  
  inflating: pgtap-1.1.0/sql/pgtap--unpackaged--0.91.0.sql  
  inflating: pgtap-1.1.0/sql/pgtap.sql.in  
   creating: pgtap-1.1.0/test/
   creating: pgtap-1.1.0/test/expected/
  inflating: pgtap-1.1.0/test/expected/aretap.out  
 extracting: pgtap-1.1.0/test/expected/build.out  
error: invalid zip file with overlapped components (possible zip bomb)
The command '/bin/sh -c apk add --update-cache         wget unzip       && wget https://api.pgxn.org/dist/pgtap/${PGTAP_VERSION}/pgtap-${PGTAP_VERSION}.zip       && unzip pgtap-${PGTAP_VERSION}.zip       && apk del wget unzip       && rm -rf /var/cache/apk/*' returned a non-zero code: 12
```

**Comment by xenoterracide** [comment]
part of my preferred fix for this would be a tarball.

**Comment by theory** [comment]
I have no idea what that's about. Alpine's `zip` thinks something's wrong with the `v1.1.0` release of pgTAP? Are you downloading it from PGXN?

**Comment by xenoterracide** [comment]
yes, from the link on the documentation. https://api.pgxn.org/dist/pgtap/1.1.0/pgtap-1.1.0.zip

**Comment by theory** [comment]
@decibel Are you using Python to zip the file? Python's zip has some issue that always triggers a bunch of warnings when PGXN operates on it; maybe Alpine's zip runs into the same problem?

**Comment by xenoterracide** [comment]
I'm using `unzip` which I don't think is python, I tried `zip`s `unzip` too

**Comment by theory** [comment]
I just tried this on `alpine:latest`, basically:

``` sh
ask add curl zip
curl https://api.pgxn.org/dist/pgtap/1.1.0/pgtap-1.1.0.zip
unzip pgtap-1.1.0.zip
```

And got no error. Same for 1.2.0. Are you still seeing this issue, @xenoterracide?

**Comment by xenoterracide** [comment]
No idea, haven't worked on this project in years
