### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by xenoterracide** [theory/pgtap#238]
would be cool if there was a pgtap docker image for all the supported postgres versions, especially if you could then use [this feature](https://docs.docker.com/develop/develop-images/multistage-build/#use-an-external-image-as-a-stage) to add it to images like postgis.

You're welcome to use my code as a base https://hub.docker.com/r/xenoterracide/postgis-pgtap/dockerfile.

**Comment by xenoterracide** [comment]
You're welcome to use my code as a base https://hub.docker.com/r/xenoterracide/postgis-pgtap/dockerfile

**Comment by dvasdekis** [comment]
The most extensive docker pgtap version I've seen is this one: https://github.com/LREN-CHUV/docker-pgtap

I use it in production myself

**Comment by theory** [comment]
Oh, _nice!_

**Comment by theory** [comment]
Since what I want to do is test things against various versions of Postgres, I've been fiddling with making a GitHub action that would spin up a specific version of Postgres in a container and install build tools, pgTAP, pg_prove, and the pgxn clients. Would be a nice environment for PGXN CICD.  I'm just getting to know actions, though, so it's slow-going, but keep an eye on theory/pgxn-action for progress.

**Comment by xenoterracide** [comment]
if you need help with actions, I might be able to put some time into it, my suggestion though is run postgres, and pgtap (etc) in different containers.

**Comment by theory** [comment]
Well, to build extensions like [semver](/theory/pg-semver), the extension needs to be built and tested in the container with the server and the pgTAP extension, so I was just gonna go with that. There is already a [pg_prove image](https://hub.docker.com/r/itheory/pg_prove/) for running tests.

**Comment by theory** [comment]
For my other PGXN extensions, I now have a GitHub CI workflow I'm pretty happy with. It's a fairly straightforward use of Docker images to test against multiple versions of PostgreSQL. Have a look at the sample [semer configuration](/theory/pg-semver/blob/master/.github/workflows/ci.yml) and [the resulting actions](/theory/pg-semver/actions). If I were to need to test with pgTAP installed, I'd simply add `postgresql-$PG_MAJOR-pgtap` to the list of apt packages to install.

**Comment by xenoterracide** [comment]
yeah, but, pgxn-tools is designed for extension testing? guess I'm thinking of an image that extends the posgres image but has pgtap extension preinstalled, going to look at the unofficial ones.

**Comment by xenoterracide** [comment]
wrote this tonight https://hub.docker.com/repository/docker/xenoterracide/postgres-pgtap/general much more advanced than the previous version. I think I'll just put it on a weekly cron job to keep it up to date.

**Comment by theory** [comment]
There is also [dalibo/docker-pgtap](https://hub.docker.com/r/dalibo/pgtap).
