### ISSUE TITLE
No documentation how how to set the password for pg_prove

### ISSUE THREAD

**Issue by xenoterracide** [theory/pgtap#239]
https://pgtap.org/documentation.html the only references to a password has nothing to do with a db password, I don't see it in `pg_prove --help` either. I personally would prefer either an environment variable or a cli --password (I know this is insecure, but in CI I don't really care because I'm connecting to an ephemeral database)

**Comment by theory** [comment]
It uses all the same interfaces as `psql`, and leaves authentication up to that client.

**Comment by xenoterracide** [comment]
sure, I figured it out but maybe it would be nice to have the section that mentioned this explicitly reference PG_PASSWORD? so that it's easier to find

**Comment by xenoterracide** [comment]
I guess I'm just looking for the documentation to say "password" somewhere, because it took me an hour to figure this out.
