### ISSUE TITLE
[Feature] functions_contains and schemas_contains

### ISSUE THREAD

**Issue by xenoterracide** [theory/pgtap#243]
I get the point of functions_are and schema_are, but it'd be nice to be a little more liberal and not "hash" the database,  this is in part due to me not wanting to check for every single added postgis/pgtest function/schema (also worth saying that both of these failed after being generated by `pg_tapgen`, no idea why they were missing stuff) I'd really only like to test those that we explicitly added.

**Comment by theory** [comment]
That's what `has_schema` and `has_function` are for.

**Comment by xenoterracide** [comment]
ah, oops, guess I was hoping for something that takes a list like all does, not a big issue for me, just ran into it because pg_tapgen got it wrong.

**Comment by theory** [comment]
Yeah, you can fake it by writing something like

```
SELECT has_schema(a) FROM UNNEST('{
    a_schema,
    other_schema
}::name[]') a;
```
