### ISSUE TITLE
Running a results_eq() test as two different users

### ISSUE THREAD

**Issue by dvasdekis** [theory/pgtap#246]
Hi folks, I'd like to run my results_eq() test as two different users, to make sure both users are getting the same output. Using `SET SESSION AUTHORIZATION 'username'` would normally let me switch users, but I can't do this within a single prepared statement.

How do I go about running a test, or part of a test, as a different user?

**Comment by theory** [comment]
Hi Dimitri. A couple of things:

1. You can `SET SESSION AUTHORIZATION 'username'` in your pgTAP file *before* you call `results_eq()`, so no need to do it in the prepared statement.

2. In the future, please post questions to the [mail list](https://groups.google.com/group/pgtap-users), as GitHub issues are intended for bug and feature tracking. Thanks!
