### ISSUE TITLE
Invalid SQL produced in uninstall_pgtap.sql

### ISSUE THREAD

**Issue by kljensen** [theory/pgtap#252]
Steps to reproduce

1. Clone repo
2. Run `make`
3. inspect `uninstall_pgtap.sql` lines for `col_not_null`

Below, I am showing the results on tag v1.1.0 and on v1.0.0. The error is in between. Notice the invalid `DROP FUNCTION` at v1.1.0. (`rg` is ripgrep.)

Using v1.1.0
```
> rg col_not_null sql/uninstall_pgtap.sql                                                                                                                           
861:DROP FUNCTION col_not_null (;
862:DROP FUNCTION col_not_null (;
```

Using v1.0.0

```
> rg col_not_null sql/uninstall_pgtap.sql                                                                                                                           861:DROP FUNCTION col_not_null ( NAME, NAME );
862:DROP FUNCTION col_not_null ( NAME, NAME, TEXT );
863:DROP FUNCTION col_not_null ( NAME, NAME, NAME, TEXT );
```

**Comment by theory** [comment]
Thanks! @nasbyj: take note of the need to put the part of create statements that are needed for drop statements on a single line; it's needed to support installation and uninstallation without using CREATE EXTENSION.

**Comment by nasbyj** [comment]
Ahh, oops. Looks like we need unit tests for extension-less install and uninstall: #253

**Comment by halostatue** [comment]
Is there a plan to release 1.2.0 at some point soon? I’m working on a tool to help our CI use of Sqitch + pgTAP and this issue just bit me, fixed almost a year ago, but present in the only released versions. I’m not sure how safe it is to use the main branch version of pgTAP, either.

**Comment by theory** [comment]
What do you think, @nasbyj? We've got a pretty good backlog of changes ready to go.

**Comment by halostatue** [comment]
@theory Please note that #270 is a regression of this particular issue and should be resolved. I’ve made a Docker image that provides Sqitch and pgtap as passthrough functions, and to make this work, I’ve had to add an additional uninstall script that deals with this. See [KineticCafe/docker-sqitch-pgtap/scripts/do_pgtap](https://github.com/KineticCafe/docker-sqitch-pgtap/blob/main/scripts/do_pgtap#L18-L24).
