### ISSUE TITLE
postgresql-13-pgtap is not available in apt repo

### ISSUE THREAD

**Issue by himanchali** [theory/pgtap#258]
Hi,

I have installed PostgreSQL-13 server and want to install postgresql-13-pgtap. But I can find only postgresql-12-pgtap. ANy idea when postgresql-13-pgtap would be available?

$ sudo apt-get install postgresql-13-pgtap
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package postgresql-13-pgtap

**Comment by theory** [comment]
You'll need to contact the maintainers of the [Postgres community Apt repo](https://wiki.postgresql.org/wiki/Apt), as they make those releases, not the members of this project.

**Comment by himanchali** [comment]
@theory Thanks !
