### ISSUE TITLE
pgtap.org documentation "What a sweet unit!" sql typo

### ISSUE THREAD

**Issue by rodrom** [theory/pgtap#260]
Hi,
I was following the documentation at the web [pgtap.org](https://pgtap.org/) and the example code for[ "What a sweet unit!"](https://pgtap.org/documentation.html#whatasweetunit) has an error in the second function.

```
CREATE OR REPLACE FUNCTION test_user(
) RETURNS SETOF TEXT AS $$
   SELECT is( nick, 'theory', 'Should have nick') FROM users;
END;
$$ LANGUAGE sql;
```
I think that the `END;` is a mistake.

**Comment by wolfgangwalther** [comment]
Already resolved in #208.
