### ISSUE TITLE
uninstall_pgtap.sql generation regression

### ISSUE THREAD

**Issue by halostatue** [theory/pgtap#270]
This appears to be a regression of #252. This specific example of errors is from a version built for PostgreSQL 9.6, but I have confirmed that this issue exists for versions built for 9.6, 10, 11, 12, and 13.

```
psql:/opt/pgtap/9/uninstall_pgtap.sql:847: ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...ble_name NAME, column_name NAME, description TEXT DEFAULT NU...
                                                             ^
psql:/opt/pgtap/9/uninstall_pgtap.sql:848: ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...ble_name NAME, column_name NAME, description TEXT DEFAULT NU...
                                                             ^
psql:/opt/pgtap/9/uninstall_pgtap.sql:849: ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...ble_name NAME, column_name NAME, description TEXT DEFAULT NU...
                                                             ^
psql:/opt/pgtap/9/uninstall_pgtap.sql:850: ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...ble_name NAME, column_name NAME, description TEXT DEFAULT NU...
                                                             ^

psql:/opt/pgtap/9/uninstall_pgtap.sql:976: ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...ON IF EXISTS finish (exception_on_failure BOOLEAN DEFAULT NU...
                                                             ^
psql:/opt/pgtap/9/uninstall_pgtap.sql:977: ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...XISTS _finish (INTEGER, INTEGER, INTEGER, BOOLEAN DEFAULT NU...
                                                             ^
```

These correspond to the following SQL:

```sql
DROP FUNCTION IF EXISTS col_is_null ( table_name NAME, column_name NAME, description TEXT DEFAULT NULL );
DROP FUNCTION IF EXISTS col_is_null ( schema_name NAME, table_name NAME, column_name NAME, description TEXT DEFAULT NULL );
DROP FUNCTION IF EXISTS col_not_null ( table_name NAME, column_name NAME, description TEXT DEFAULT NULL );
DROP FUNCTION IF EXISTS col_not_null ( schema_name NAME, table_name NAME, column_name NAME, description TEXT DEFAULT NULL );
DROP FUNCTION IF EXISTS finish (exception_on_failure BOOLEAN DEFAULT NULL);
DROP FUNCTION IF EXISTS _finish (INTEGER, INTEGER, INTEGER, BOOLEAN DEFAULT NULL);
```

**Comment by theory** [comment]
I am not able to replicate this issue. I just tired with 13 and 14, and both properly remove the `DEFAULT NULL` bit. I have:

``` sql
DROP FUNCTION col_is_null ( table_name NAME, column_name NAME, description TEXT );
DROP FUNCTION col_is_null ( schema_name NAME, table_name NAME, column_name NAME, description TEXT );
DROP FUNCTION col_not_null ( table_name NAME, column_name NAME, description TEXT );
DROP FUNCTION col_not_null ( schema_name NAME, table_name NAME, column_name NAME, description TEXT );
DROP FUNCTION finish (exception_on_failure BOOLEAN);
DROP FUNCTION _finish (INTEGER, INTEGER, INTEGER, BOOLEAN);
```

What OS are you on, and what version of `sed`?

**Comment by theory** [comment]
I've just submitted #290, which replaces `sed` with Perl (which was already being used to create the script!). I suspect that will fix your issue. Can you confirm , @halostatue?

**Comment by halostatue** [comment]
I’ll need to test this, but I _suspect_ that it’s a difference between versions of `sed` and that switching to Perl for everything is going to be a better choice. Dumb question: if you’re switching to `perl` instead of `sed`, is there a reason to keep `grep` instead of processing the entire thing with `perl`?

**Comment by theory** [comment]
Maybe not, but the reason I left it is that the Perl processes the stuff in reverse order (so it uninstalls in the reverse of the order it was installed). Would just have to load it all and reverse it, so just lazily left the grep to produce the list and it just reverses the input. But now that I look at it again, I realize it could probably open the file and read it in reverse order. Never don't that before…

**Comment by theory** [comment]
Yep, one more pass at now #290 dropped the use of `grep` there, too. Thanks for the prod!

**Comment by halostatue** [comment]
I had noticed this during the repeated build of https://github.com/KineticCafe/docker-sqitch-pgtap, when I reported it. I’m using this rather than the official build because I wanted to include pgtap in the same docker image.

**Comment by halostatue** [comment]
It looks good overall.
