### ISSUE TITLE
installing on different instance postgresql

### ISSUE THREAD

**Issue by andreas-trvlk** [theory/pgtap#271]
Let me give a little bit of background. I have 2 instances of postgresql in my mac. One is version 13 which uses standard path. eg. `/usr/local/Cellar/postgresql`. Another one is version 9.6 which uses specific path, eg `/usr/local/Cellar/postgresql@9.6`.

After I followed the installation procedure, I don't find `pgtap.control` in the extension directory of postgres 9.6, but it can be found in the normal postgres path.

Is there any way to install pgtap in the different instance?

**Comment by theory** [comment]
You need to install it again either with the other instance's bin directory in your path, or else set `PG_CONFIG` as descried in the README:

```
env PG_CONFIG=/path/to/pg_config make && make install && make installcheck
```
