### ISSUE TITLE
Add regexp comparison support on errmsg parameter on throws_ok function

### ISSUE THREAD

**Issue by stephane-klein** [theory/pgtap#273]
What do you think to add regexp comparison support on `errmsg` parameter on [`throws_ok`](https://github.com/theory/pgtap/blob/9535cbaee6f472c73875bc878c4f61f288b711c1/sql/pgtap.sql.in#L657) function.

For instance, I would write:

```
    SELECT throws_ok(
    $$
        SELECT * FROM my_function()
    $$,
        'P0001',
        'Internal error: planned execution datetime range .* should be planned after the notice period .*',
        'should test entry notice period is not correct'
    );
```

Best regards,
Stéphane

**Comment by Its-Alex** [comment]
Up?

**Comment by theory** [comment]
There's [`throws_matching()`](https://pgxn.org/dist/pgtap/doc/pgtap.html#throws_matching.).
