### ISSUE TITLE
Install Issues with Docker PG container could use Install Notes

### ISSUE THREAD

**Issue by jed-walker-icd** [theory/pgtap#275]
Hi,
I’m working a project where I develop locally using a PostgreSQL docker container. Doing the install, I ran into errors that are apparently because I’ve installed pgtap in my ubuntu not in the Docker PG container. 
It would sure be nice if the install instructions made a note about that.
David Wheeler provided me the solution which makes sense (just haven't had time to test it out)
This google group discussion has the details.
https://groups.google.com/g/pgtap-users/c/4rQCm5NAWIc

**Comment by theory** [comment]
Does this seem sufficient?

``` patch
--- a/doc/pgtap.mmd
+++ b/doc/pgtap.mmd
@@ -52,7 +52,8 @@ Installation
 ============
 
 pgTAP must be installed on a host with PostgreSQL server running; it cannot
-be installed remotely.
+be installed remotely. If you're using PostgreSQL in Docker, you need to install
+pgTAP inside the Docker container.
 
 To install pgTAP into a PostgreSQL database, just do this:
 
```
