### ISSUE TITLE
Test Failures on PostgreSQL 14

### ISSUE THREAD

**Issue by theory** [theory/pgtap#277]
@df7cb reports in a comment on #276:

> Debian's test runner creates those extensions before invoking installcheck:
> https://salsa.debian.org/postgresql/pgtap/-/blob/master/debian/tests/installcheck
> 
> But even with that, the tests are failing on PG14:
> https://pgdgbuild.dus.dg-i.net/view/Binaries-Beta/job/pgtap-binaries-beta/14/architecture=amd64,distribution=sid/console
> ```
> 22:15:25 --- /<<PKGBUILDDIR>>/test/expected/hastap.out· 2019-11-25 19:03:44.000000000 +0000
> 22:15:25 +++ /<<PKGBUILDDIR>>/results/hastap.out·       2021-08-12 20:15:19.388123291 +0000
> 22:15:25 @@ -500,22 +500,40 @@
> 22:15:25  ok 498 - has_operator( left, name, right ) fail should fail
> 22:15:25  ok 499 - has_operator( left, name, right ) fail should have the proper description
> 22:15:25  ok 500 - has_operator( left, name, right ) fail should have the proper diagnostics
> 22:15:25 -ok 501 - has_leftop( schema, name, right, result, desc ) should pass
> 22:15:25 +not ok 501 - has_leftop( schema, name, right, result, desc ) should pass
> 22:15:25 +# Failed test 501: "has_leftop( schema, name, right, result, desc ) should pass"
> 22:15:25 +#         have: false
> 22:15:25 +#         want: true
> ...
> ```
> 
> Any chance we can get a release that fixes these issues?

I installed PostgreSQL 14 on my Mac and confirmed the failures:

```
============== running regression test queries        ==============
test build                        ... ok          582 ms
test create                       ... ok          306 ms
test aretap                       ... ok         3953 ms
test check                        ... ok          147 ms
test cmpok                        ... ok          101 ms
test coltap                       ... ok          543 ms
test do_tap                       ... ok          107 ms
test enumtap                      ... ok          271 ms
test extension                    ... ok          440 ms
test fktap                        ... ok          715 ms
test functap                      ... FAILED (test process exited with exit code 3)       33 ms
test hastap                       ... FAILED     2416 ms
test index                        ... ok          770 ms
test inheritance                  ... ok         1200 ms
test istap                        ... ok          110 ms
test matching                     ... ok           78 ms
test moretap                      ... ok          123 ms
test ownership                    ... ok          866 ms
test partitions                   ... ok          261 ms
test performs_ok                  ... ok           80 ms
test performs_within              ... ok           89 ms
test pg73                         ... ok           87 ms
test pktap                        ... FAILED      215 ms
test policy                       ... ok          393 ms
test privs                        ... ok          807 ms
test resultset                    ... ok         2456 ms
test roletap                      ... ok          279 ms
test ruletap                      ... ok          385 ms
test runjusttests                 ... ok          123 ms
test runnotests                   ... ok          181 ms
test runtests                     ... ok          626 ms
test throwtap                     ... ok          346 ms
test todotap                      ... ok          153 ms
test trigger                      ... ok          298 ms
test unique                       ... FAILED      236 ms
test usergroup                    ... ok          249 ms
test util                         ... ok          100 ms
test valueset                     ... ok         1691 ms

=======================
 4 of 38 tests failed. 
=======================
```

**Comment by theory** [comment]
@df7cb Can you try #278?

**Comment by matthieu-foucault** [comment]
I see this was closed but no release tag yet. Are there still outstanding issues to be resolved for postgres 14, or are we good to use it with pgTap (at least the `master` branch until there's a tag)?

**Comment by theory** [comment]
I think it's safe to use master, #278 notwithstanding. I hope Jim or I can make a release in the next week.

**Comment by theory** [comment]
v1.2.0 pushed to GitHub and PGXN now, @df7cb.

**Comment by df7cb** [comment]
Packages uploaded, thanks!
