### ISSUE TITLE
Need to distinguish between functions and procedures

### ISSUE THREAD

**Issue by hettie-d** [theory/pgtap#280]
At the moment, there are no separate functions to check for the existence of procedure vs. function. Although the prokind column is present in the tap_funky view, it is not used to distinguish between functions and procedures. Would it be possible to have separate tests for that?

**Comment by c2main** [comment]
Hi @theory 

I would like to consider reopening this issue to address `*_are()` family.

I think the current `functions_are()` should limit itself to functions, not procedures.

And having a dedicated `procedures_are()` to go with it. 

The patch is trivial with regression, if we want to keep same behavior for existing code then I'm unsure what would work best for existing users of `functions_are()`.
