### ISSUE TITLE
Test output from runtests() can be out of order

### ISSUE THREAD

**Issue by chipilov** [theory/pgtap#286]
Running pgTAP using xUnit style functions and runtests() (as described here: https://pgtap.org/documentation.html#whatasweetunit) seems to return the TAP output as an unordered set of strings (indeed, the source for runtests() shows that it returns SETOF TEXT).

I've tried running tests using several SQL clients (pgAdmin, TablePlus, Supabase dashboard) and all of them show the TAP output in a random order.

Shouldn't runtests() (and any functions that it calls such as _runner()) return an array of text OR a SETOF records that have ids so they can be sorted by id?

**Comment by theory** [comment]
If you use PL/pgSQL, functions should return results in the order of each call to `RETURN NEXT`. If you're returning a query, yes you would need a way to sort it before returning it.

Can you post an example of a function that returns the results in random order?

**Comment by chipilov** [comment]
Indeed, I am using PL/pgSQL functions for my tests and I use ```RETURN NEXT``` within them, but I still get the results out of order.

Here are my test functions (some unnecessary details are ommited):

```
CREATE OR REPLACE FUNCTION test.test_invalid_user_creation_request()
RETURNS SETOF TEXT
AS $$
BEGIN
  RETURN NEXT
    throws_ok(
      'SELECT public.create_user_profile(''{ "haha": 1 }'')',
      'P0001',
      'Invalid request data for create_user_profile',
      'Profile creation should throw on malformed JSON'
    );
END
$$
LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION test.test_valid_user_creation_request()
RETURNS SETOF TEXT
AS $f$
DECLARE
  request jsonb;
BEGIN
  -- ommitting some unneecssary details

  request = '
    {
      "personalData": {
        "name": "John Doe",
        "phone": "001 123456789"
      },
      "subscription": {
        "currentCode": "BASIC"
      }
    }'::jsonb;

  PERFORM public.create_user_profile(request);

  RETURN NEXT
    results_eq(
      $$
        SELECT access_level, organization_id, name, address, phone
        FROM user_profile
      $$,
      $$
        VALUES
        (
          'BASIC'::varchar(32),
          NULL::uuid,
          'John Doe'::varchar(128),
          '001 123456789'::varchar(32)
        )
      $$,
      'user profile should contain the newly created user profile'
    );
END
$f$
LANGUAGE plpgsql;
```

When I run the tests using ``` SELECT * from runtests('test'::name);```, I get the following output:
```
    # Subtest: test.test_invalid_user_creation_request()
    ok 1 - Profile creation should throw on malformed JSON
    1..1
ok 1 - test.test_invalid_user_creation_request
    # Subtest: test.test_valid_user_creation_request()
    ok 1 - user profile should contain the newly created user profile
    1..1
ok 2 - test.test_valid_user_creation_request
1..2
```

NOTICE, how the ```ok 1 - test.test_invalid_user_creation_request``` line is followed by the line about the subtests of the other test (```# Subtest: test.test_valid_user_creation_request()```)

Instead, I expect to see something like this:
```
1..2
ok 1 - test.test_invalid_user_creation_request
    # Subtest: test.test_invalid_user_creation_request()
    ok 1 - Profile creation should throw on malformed JSON
    1..1
ok 2 - test.test_valid_user_creation_request
    # Subtest: test.test_valid_user_creation_request()
    ok 1 - user profile should contain the newly created user profile
    1..1
```

Am I missing something here?

**Comment by theory** [comment]
I think the issue is not ordering gos much as indentation. The way it works is, first there is an (unfortunately indented) diagnostic output announcing the start of a nested test. This is followed by those subtests. After the subtests finish, a report of the plan is output (`1..1`), and then this outcome of all the subtests recorded as a single (unindented) result. So this is the
`test.test_invalid_user_creation_request` test:

```
    # Subtest: test.test_invalid_user_creation_request()
    ok 1 - Profile creation should throw on malformed JSON
    1..1
ok 1 - test.test_invalid_user_creation_request
```

And then this is the `test.test_valid_user_creation_request` test:

```
    # Subtest: test.test_valid_user_creation_request()
    ok 1 - user profile should contain the newly created user profile
    1..1
ok 2 - test.test_valid_user_creation_request
```

Unindenting the diagnostic announcing each subtest would help a lot, but alas could break a lot of tests in the wild. See #264 for an in-depth discussion.

**Comment by chipilov** [comment]
I see, thanks a lot for the explanation @theory!
