### ISSUE TITLE
Misleading Installation Instructions

### ISSUE THREAD

**Issue by machineghost** [theory/pgtap#301]
The instructions on https://pgtap.org/documentation.html#installation say:

> To install pgTAP into a PostgreSQL database, just do this:

    make
    make install
    make installcheck

Shouldn't that say:

> To install pgTAP, first download the source code from ___some_url___.  Then, run the following commands at the command line, from inside the folder where you downloaded pgTAP:

    make
    make install
    make installcheck

P.S. And of course, I realize that using `make` should already be second nature for a C dev.  But ... C devs aren't the only ones using PostgreSQL. Developers coming from interpreted language backgrounds need you to spell things out more.

P.P.S. On Linux installing pgTAP is as simple as:

    sudo apt-get install pgtap

It would seem like that's worth noting in the documentation also.

**Comment by theory** [comment]
Well that's generated from doc/pgtap.mmd, which ships with the source code. Would not object to adding additional wording or links to binary installers, though, if you wanted to make a pull request.

**Comment by theory** [comment]
Did you want to submit a PR for the, @machineghost?

**Comment by machineghost** [comment]
My apologies; somehow this fell off my radar :(

**Comment by theory** [comment]
no worries, I cribbed from your draft :-)
