### ISSUE TITLE
Question: pgTap on Greenplum?

### ISSUE THREAD

**Issue by fomcl** [theory/pgtap#304]
Hi,

I was wondering if you know whether `pgtap` can also be used on Greenplum (database cluster based on postgresql). We're running PostgreSQL 9.4 + Centos 7, if that matters.

Thanks!

Albert-Jan

**Comment by theory** [comment]
9.4, wow! Honestly I don't know. Probably? Try it and see!

**Comment by fomcl** [comment]
Hi, it appears to work! :-) We had to install it on all database segments, which makes sensr. I only checked `is()`. I did get warnings about missing extensions `isn` and `ltree`. 

Do I need to install `pg_trove` separately?

**Comment by theory** [comment]
The `isn` and `ltree` warnings are not from pgTAP, which does not require them. Do you mean `pg_prove`? Yes, that's a Perl app. There is also a [pg_prove docker image](https://hub.docker.com/r/itheory/pg_prove).
