### ISSUE TITLE
How to use the return value of an insert?

### ISSUE THREAD

**Issue by user72356** [theory/pgtap#305]
Hello! 

I have a test where I'm inserting a row, then I need to retrieve the id of the inserted row in order to run subsequent tests. Something like:

```
SELECT isnt_empty
($$
    INSERT INTO private.replicache_space (id, "version")
    VALUES (gen_random_uuid(), 1)
    RETURNING id as organization_id -- Trying to capture this generated column and use later
$$);

SELECT isnt_empty
($$
    INSERT INTO private.organization (id, name, replicache_version)
    VALUES (organization_id, 'Microsoft', 1) -- I want to use the generated column here
    RETURNING id
$$);

(...)
```

I've tried everything and I can't figure out how to capture the generated id in order to run all the other tests. Help!

**Comment by theory** [comment]
If you're on a new enough version of Postgres, you can use a CTE, something like (untested, you get the idea):

``` sql
WITH insertion AS (
    INSERT INTO private.replicache_space (id, "version")
    VALUES (gen_random_uuid(), 1)
    RETURNING id as organization_id
)
SELECT collect_tap(
    ok(insertion.organization_id, 'Should have new organization ID'),
    is(insertion.organization_id, 12, 'Should have ID 12')
);
```

**Comment by user72356** [comment]
This works for one test immediately after the CTE but I need to reuse this variable for a whole battery of tests later...

**Comment by theory** [comment]
Then perhaps store the results in a temporary table and then read them from that table in subsequent tests?

**Comment by user72356** [comment]
Yes that's what I ended up doing, I was hoping for a more straight forward variable assigment trick, but that will do. Thanks!

**Comment by theory** [comment]
There might be a way to do it, though my psql-foo is a bit out-of-date. @depesz might have a suggestion.

**Comment by depesz** [comment]
Sure. As long as all happens in single connection, you can:

    select set_config('temp.whatever', '123', false);

and then, in any other query, you can use it like:

    select current_setting('temp.whatever');

name can be anything, but has to contain '.'

**Comment by theory** [comment]
So something like:

``` sql
SELECT lives_ok($$
    WITH insertion AS (
        INSERT INTO private.replicache_space (id, "version")
        VALUES (gen_random_uuid(), 1)
        RETURNING id as org_id
    )
    select set_config('test.org_id', insertion.org_id::text, false)
$$, 'Insert new organization);

SELECT ok(
    current_setting('test.org_id'),
    'Should have new organization ID'
);
```
