### ISSUE TITLE
Is Postgres 15 supported?

### ISSUE THREAD

**Issue by oramor** [theory/pgtap#308]
Hello. I'm trying to install pgtap on Oracle Linux. Having solved some problems I had one:
```
[root@pg-dev pgtap-1.2.0]# make
GNUmake running against Postgres version 15.2, with pg_config located at /usr/bin
Makefile:126: /usr/pgsql-15/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target '/usr/pgsql-15/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.
```

I tried:
`yum install postgresql-devel`

But this development kit is only for 14 version. Therefore (or maybe for another reason) pgxs.mk still not exists.
Can I solve it?

**Comment by theory** [comment]
Yes, pgTAP supports Postgres 15. You will need to install the development tooling from the same source from which you installed Postgres. If Oracle Linux `yum` is giving you 14 and you are using 15, where dig 15 come from? Did you configure `yum` to use `yum.postgresql.org` just to install it, for example?
