### ISSUE TITLE
New release with PG16 support

### ISSUE THREAD

**Issue by df7cb** [theory/pgtap#314]
Hi,

PG 16beta3 will be out tomorrow. Is there any chance of getting a new pgtap release tagged? I see compatibility has already been fixed, just not released.

**Comment by theory** [comment]
I'll put some time into it this week; it has been a while!

**Comment by theory** [comment]
I'm updating the pgxn-tools Docker image, but Weirdly getting [these errors](https://github.com/pgxn/docker-pgxn-tools/actions/runs/5849550312/job/15857997632) running `sudo sh apt.postgresql.org.sh -i -t -v 16`.

```
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 postgresql-16 : Depends: postgresql-client-16 but it is not going to be installed
                 Depends: postgresql-common (>= 252~) but 248 is to be installed
                 Depends: libpq5 (>= 16~~) but 15.3-0+deb12u1 is to be installed
                 Recommends: sysstat but it is not going to be installed
 postgresql-server-dev-16 : Depends: libpq-dev (>= 16~~) but 15.3-0+deb12u1 is to be installed
                            Depends: postgresql-client-16 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Is this issue specific to Bookworm, perhaps?

**Comment by df7cb** [comment]
Does running without `-t` work better? The *-pgdg-testing suites have a lower apt pin priority so apt is in some situations reluctant to pick packages from there.

**Comment by theory** [comment]
No, I added the `-t` to try to fix this issue.

**Comment by theory** [comment]
WTF, that did fix it. o_O.

**Comment by theory** [comment]
Okay, got that deployed and the v16 tests now pass, but not the upgrades, which fail on [this command](https://github.com/theory/pgtap/actions/runs/5860548993/job/15888859878):

```
$ apt-get install -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" postgresql-16 postgresql-server-dev-16

Package 'postgresql-server-dev-16' has no installation candidate
```

I tried removing `postgresql-server-dev-16`, but it still [errors with](https://github.com/theory/pgtap/actions/runs/5860672948/job/15889239342):

```
Package 'postgresql-16' has no installation candidate
```

Works okay with 15. Maybe there's some way to use `apt.postgresql.org.sh` instead? This is to install a second version alongside the first and run it on a separate port so we an test an upgrade…

**Comment by theory** [comment]
Yup, that did it. Thanks!

**Comment by theory** [comment]
[Boom](https://github.com/theory/pgtap/actions/runs/5860984284)

**Comment by theory** [comment]
[Done](/theory/pgtap/releases/tag/v1.3.0)

**Comment by df7cb** [comment]
Thanks, the Debian packages are also happy now!
