### ISSUE TITLE
How to install and use pgtap in different schema?

### ISSUE THREAD

**Issue by blasterpistol** [theory/pgtap#325]
I want to install pgtap v1.3.1 on the `tap` schema.

What I am doing:
```sql
create schema tap;
create extension pgtap schema tap;
select tap.is(10, 10);
```
What I get:
```
ERROR:  function is(integer, integer, unknown) does not exist
LINE 2:     SELECT is( $1, $2, NULL);
                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  
    SELECT is( $1, $2, NULL);

CONTEXT:  SQL function "is" during inlining

```

What is the correct way to use pgtap from another schema?

**Comment by theory** [comment]
You need to add `tap` to the search path:

```
set search_path = tap,public;
```

This is because none of the functions that call other functions (as in your example, where `is(any, any)` calls `is(any, any, text)`) use the schema name to call them.
