### ISSUE TITLE
passing the name of a test directory to pg_prove return 'Result: NOTESTS'

### ISSUE THREAD

**Issue by michelle0809** [theory/pgtap#326]
OS: Win10
pgTAP Version: 1.2.0
pg_prove Version: 3.36
PostgreSQL Version: 13

According to the official documentation, it is allowed to pass the test folder path to pg_prove.
But when I try to do this, it return 'Result: NOTESTS'.
![image](https://github.com/theory/pgtap/assets/71964831/c075fecb-6951-4b32-9371-fd5759d9794d)

There is only one file test_function.sql in the folder 'test'.
Passing the file name to pg_prove works, but passing the test directory does not.
How can I correct my pg_prove command?

**Comment by theory** [comment]
You need the `--recurse` option. From [the docs](https://pgtap.org/pg_prove.html):

```
    "--recurse"
          pg_prove --recurse tests/
          pg_prove --recurse sql/

        Recursively descend into directories when searching for tests. Be
        sure to specify "--ext" if your tests do not end in ".pg". Not
        relevant with "--runtests".
```
