### ISSUE TITLE
Cannot install pgTAP 1.3.1

### ISSUE THREAD

**Issue by datafoo** [theory/pgtap#327]
As explained in https://github.com/NixOS/nixpkgs/issues/272232, I cannot install pgTAP 1.3.1 on NixOS:

```bash
[me@mymachine:~/dev/postgresql-cluster]$ nix# psql -U postgres -h localhost
psql (15.4)
Type "help" for help.

postgres=# SELECT * FROM version();
                                   version                                    
------------------------------------------------------------------------------
 PostgreSQL 15.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 12.3.0, 64-bit
(1 row)

postgres=# SELECT * FROM pg_available_extensions WHERE name = 'pgtap';
 name  | default_version | installed_version |           comment           
-------+-----------------+-------------------+-----------------------------
 pgtap | 1.3.1           |                   | Unit testing for PostgreSQL
(1 row)

postgres=# CREATE EXTENSION pgtap;
ERROR:  could not access file "$libdir/pgtap": No such file or directory
```

Is this due to pgTAP or the way pgTAP was packaged on NixOS?

**Comment by theory** [comment]
On Windows, try v1.3.0. v1.3.1 adds a shared library that must be compiled, as it was the only way to properly parse type names, as discussed in #315. I do not know how one compiles the library on Windows.

@datafoo How did you install pgTAP on nix? Is it possible their packaging needs to be updated to add the shared library?

**Comment by theory** [comment]
Added a comment to NixOS/nixpkgs#272232 about the need to install the shared library.
