### ISSUE TITLE
Function to check procedure privileges

### ISSUE THREAD

**Issue by hettie-d** [theory/pgtap#329]
Is it possible to add a function to check procedure privileges similar to function_privileges_are? 

Thanks!

**Comment by theory** [comment]
I'm sure it is, probably a straightforward refactoring of the function tests.

**Comment by theory** [comment]
Actually it looks like the existing function should work:

```postgrsql
```

**Comment by hettie-d** [comment]
It gave me an error: "function does not exist', but it could be a user error! I will double-check and report!
