### ISSUE TITLE
Bad links in documentation

### ISSUE THREAD

**Issue by vickkhera** [theory/pgtap#333]
Hi David,

Glad to see you've issued some updated releases recently.  There are a couple of bad links in the documentation.

Looking at the page https://pgtap.org/documentation.html

The sentence: _This is similar to how [PGUnit](http://en.dklab.ru/lib/dklab_pgunit/) works._ the link to PGUnit just times out and has for several days. I'm suspecting it is no longer valid.  There is a second reference in the sentence _This most closely emulates the xUnit testing environment, similar to the functionality of [PGUnit](http://en.dklab.ru/lib/dklab_pgunit/)._

The sentence _The source code for pgTAP is available on [GitHub](https://github.com/theory/pgtap/tree/). Please feel free to fork and contribute!_ links to a page not found.

**Comment by theory** [comment]
Thank you!
