### ISSUE TITLE
Add useful negation function tests

### ISSUE THREAD

**Issue by theory** [theory/pgtap#38]
- `isnt_definer()`
- `isnt_strict()`
- `isnt_aggregate()`

**Comment by rodo** [comment]
`isnt_strict()` is already done that a good point, the two others left are quite easy to code, I'll have a look

**Comment by rodo** [comment]
`isnt_member_of` could be useful too, don't know if I'll add in the same PR or not, depends on  when the already mergeable PR will be merge ;-)

**Comment by theory** [comment]
All of these functions have been added.
