### ISSUE TITLE
enum_has_labels() Sorts Added Labels Incorrectly.

### ISSUE THREAD

**Issue by theory** [theory/pgtap#60]
Create an enum:

    CREATE TYPE foo AS ('alice', 'barbara', 'cathy');

Insert a new value in the middle:

    ALTER TYPE foo ADD VALUE 'brenda' AFTER 'barbara';

This call to `enum_has_labels()` will fail:

    SELECT enum_has_labels('foo', ARRAY['alice', 'barbara', 'brenda', 'cathy']);

Because it will fetch "cathy" before "brenda". Most likely need to sort the values by some other method than currently, and perhaps only on versions of Postgres since `ADD VALUE` was added.

**Comment by cbandy** [comment]
Bleh! `ERROR:  ALTER TYPE ... ADD cannot run inside a transaction block`

Any suggestions for how to write a test for this (that I may try to submit a fix)?

**Comment by theory** [comment]
Looks like we need to update `enum_has_labels()` to sort on `e.enumsortorder`, but only on 9.1 and higher. Will need to create a `compat/install-9.0.patch` file to support older versions.

**Comment by cbandy** [comment]
Yah, I tried something without tests, but I got stuck on the compat patches anyway:

- https://github.com/cbandy/pgtap/compare/theory:master...cbandy:enum-sortorder-plpgsql
- https://travis-ci.org/cbandy/pgtap/builds/49029706

**Comment by theory** [comment]
Give that a try, @cbandy.

**Comment by cbandy** [comment]
Looks good. Are there any tools or instructions for creating/regenerating the compat patches?
