### ISSUE TITLE
GRANT SELECT TO PUBLIC on tap_funky and pg_all_foreign_keys

### ISSUE THREAD

**Issue by theory** [theory/pgtap#67]
These views should be readable by whoever calls the pgTAP functions, not just the user who created them.

**Comment by cbandy** [comment]
I'm confused. I see grant statements in the 0.93.0--0.94.0 changes of the [master branch](https://github.com/theory/pgtap/blob/master/sql/pgtap--0.93.0--0.94.0.sql), but not the [v0.94.0 tag](https://github.com/theory/pgtap/blob/v0.94.0/sql/pgtap--0.93.0--0.94.0.sql).

**Comment by theory** [comment]
This bug is still open.

**Comment by cbandy** [comment]
Is there work to be done on master?

**Comment by theory** [comment]
Yeah, said `GRANT` statements should be added.

**Comment by theory** [comment]
Sorry, I put them into the wrong upgrade file in b4f41455. Fixed in db04889. Will be in the next release for sure (soon).
