### ISSUE TITLE
How to test a "setter" function using results_eq()

### ISSUE THREAD

**Issue by bglanville** [theory/pgtap#75]
(NB - I am using the scripts method and pg_prove to run my tests, not the xUnit function style)

I am trying to test the result from a 'setter' function (an API that is used to INSERT a record into a table) using results_eq(). My API returns the value of the PK that is generated by the SERIAL PRIMARY KEY attribute of the table that I am inserting into. 

I hoped to test this in a single test using results_eq and so the first parameter I pass in is a SELECT from the setter function, the second argument is a SELECT that retrieves the primary key directly from the table. The problem is that because they are both (eventually) treated as cursors, when the second cursor is OPENed the function has yet to be called (and so the row doesn't yet exist in the table) and so the second query never sees the new row that is created. Here is a block of code that represents the problem (the call to the function has been replaced by a regular INSERT statement for brevity):

```
CREATE TABLE pgtap_results_eq_test (pgTest_id SERIAL PRIMARY KEY, name TEXT);
COMMIT;

BEGIN;
SELECT plan(1);

SELECT results_eq($$INSERT INTO pgtap_results_eq_test(name) VALUES ('TEST') RETURNING pgTest_id$$, $$SELECT pgTest_id FROM pgtap_results_eq_test WHERE name = 'TEST'$$,           'Check that the PK created is the one we expect');

SELECT * FROM finish();
ROLLBACK;

DROP TABLE pgtap_results_eq_test;
COMMIT;
```

I have found a workaround where I can call the function up front and use \gset to catch the return value into a variable:

```
INSERT INTO pgtap_results_eq_test(name) VALUES ('TEST2') RETURNING pgTest_id AS v_id
\gset

SELECT is(ARRAY(SELECT pgTest_id FROM pgtap_results_eq_test WHERE name = 'TEST2'), ARRAY[:v_id],
                          'Check that the PK created is the one we expect');
```

But somehow that seems a hack!

Of course, there could be another perfectly good solution using the existing APIs which I would love to have pointed out to me!

**Comment by stephane-klein** [comment]
@theory some news abount:

> Personally, I think that the \gset solution is a very good one. I always wanted a way to get return values into psql variables for this sort of thing.

?

**Comment by theory** [comment]
It shipped in Postgres 9.3. Check out [@depsz's post](https://www.depesz.com/2013/02/03/waiting-for-9-3-create-a-psql-command-gset-to-store-query-results-into-psql-variables/) for a quick intro.

**Comment by karolzlot** [comment]
@theory Such variables can be printed using `\echo` but not when using `diag()`, is it a bug?

**Comment by karolzlot** [comment]
I see it works, but apostrophes are necessary, like this:
```sql
SELECT diag(:'avar')
```
