### ISSUE TITLE
Ubuntu package Version?

### ISSUE THREAD

**Issue by apolishch** [theory/pgtap#82]
The Ubuntu Package version still sits on 0.90. Are there any plans to move them onto 0.94? Is this even the right place to request that? Without that we can not really make use of this. We run Postgres 9.3 on Ubuntu.

Barring that, detailed steps to work around this would be great.

**Comment by theory** [comment]
No, I think you want to complain [here](http://bugs.debian.org/pgtap).

**Comment by apolishch** [comment]
Thank you @theory 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784686
