### ISSUE TITLE
coverage

### ISSUE THREAD

**Issue by apolishch** [theory/pgtap#85]
Is there any meaningful method of measuring coverage of pg tests? Any ideas on what that would look like?

**Comment by theory** [comment]
Not to my knowledge. You wight want to post to the [mail list](http://lists.pgfoundry.org/mailman/listinfo/pgtap-users) to see if anyone in the community has a good idea.

**Comment by lastlink** [comment]
There is SQLCover for the tSQLt sql server testing framework that uses power shell to call its dll. It leverage some kind of sql server tracing to get line coverage.
