### ISSUE TITLE
results_eq variant that accepts parameters

### ISSUE THREAD

**Issue by studdugie** [theory/pgtap#88]
The current results_eq already works with prepared statements. This request hopes that you'll extend that functionally by creating a variant that additionally accepts an hstore or JSON object literal string containing parameters to be passed to the prepared statement. The signature may look as follows:
result_eq(:name, :values, :result, :description)
where
:name - the prepared statement's name

:values - a HSTORE or JSON object string literal containing the values to be used when executing the prepared statement and their data type names

:result - cursor, VALUES string, or array (i.e., same behavior as original)

:description - same behavior as original

**Comment by theory** [comment]
That's a good idea. Will it work if the types of the params to the prepared statements are varied? Because an array has to have elements of the same types.

**Comment by studdugie** [comment]
Forget what I said before about `JSON/HSTORE` because a `TEXT[]` fits the bill just fine. The way I'm picturing it in my mind is below and I hope it answers your question.:

Given the following prepared statement:
```SQL
PREPARE _test_foo AS SELECT * FROM foo WHERE bar=$1 AND bas BETWEEN $2 AND now();
```
where $1 is an `INTEGER` and $2 is a `TIMESTAMPTSZ`.

Then assume result_eq is invoked as follows:
```SQL
SELECT result_eq (
  '_test_foo',
  ARRAY['3::INT',  $$'2015-01-01 13:00:00'::TIMESTAMPTSZ$$],
  'some_cursor'::refcursor,
  'foobar test OK'
);
```
Then `result_eq` would generate and execute the following SQL command:
```SQL
EXECUTE _test_foo (3::INT, '2015-01-01 13:00:00'::TIMESTAMPTSZ);
```

**Comment by theory** [comment]
Ah, so the values would be quoted and use casting as appropriate? Might work okay. Curious to know if anyone else would want it. Would you mind posting to [the mail list](http://pgfoundry.org/mail/?group_id=1000389) to see if other folks would like such a feature?

Of course, today you can just run:

    SELECT results_eq(
        $$ EXECUTE _test_foo(3::INT, '2015-01-01 13:00:00'::TIMESTAMPTZ) $$,
        'foobar test OK'
    );

Which isn't really that different, is it?

**Comment by studdugie** [comment]
You are right. It's obvious now. Forget my request because problem solved.

Thanks.

Dane

**Comment by theory** [comment]
Thanks!
