### ISSUE TITLE
0.95 exposes _time_trial type

### ISSUE THREAD

**Issue by mestudd** [theory/pgtap#89]
In an empty database, the types_are check fails because pgtap created a type that is visible in the public schema:

    -bash-3.2$ createdb pgtap_test
    -bash-3.2$ psql pgtap_test
    pgtap_test=# CREATE EXTENSION pgtap;
    CREATE EXTENSION
    pgtap_test=# BEGIN;
    BEGIN
    pgtap_test=# SELECT plan(1);
     plan
    ------
     1..1
    (1 row)
    
    pgtap_test=# SELECT types_are('{}');
                                      types_are
    -----------------------------------------------------------------------------
     not ok 1 - Search path "$user",public should have the correct types        +
     # Failed test 1: "Search path "$user",public should have the correct types"+
     #     Extra types:                                                         +
     #         _time_trial_type
    (1 row)
    
    pgtap_test=# \dT
               List of data types
     Schema |       Name       | Description
    --------+------------------+-------------
     public | _time_trial_type |
    (1 row)
    
    pgtap_test=# DROP EXTENSION pgtap;
    DROP EXTENSION
    pgtap_test=# \dT
         List of data types
     Schema | Name | Description
    --------+------+-------------
    (0 rows)

Running postgresql 9.2 on centos 5. Postgres and pgTap installed with PGDG yum repository: postgresql92-9.2.13-1PGDG.rhel5; pgtap92-0.95.0-1.rhel5

**Comment by cbandy** [comment]
You can choose the schema in which to install the pgTAP types and functions; see the docs for [`create extension`](http://www.postgresql.org/docs/current/static/sql-createextension.html).

**Comment by theory** [comment]
Right, the same is true of the other `_are()` test functions: they will match other objects created by pgTAP if they are run against the schema pgTAP is in (or if you're relying on visibility and pgTAP is in a visible schema. The solution is to either put pgTAP into a schema not included in the path, or to specify a schema that does not include pgTAP in your tests.
