### ISSUE TITLE
Exception test failing in 9.5 but not 9.4

### ISSUE THREAD

**Issue by keithf4** [theory/pgtap#95]
Been staring at this all day and can't seem to figure out the problem. May just be doing some rubber duck debugging reporting the issue here, but right now I'm stumped why this is happening. Running version 0.96.0 of pgtap.

The `test-id-id-id-subpart.sql` in my pg_partman extension (https://github.com/keithf4/pg_partman) is failing one test in 9.5 but passing in 9.4 (lowest supported version). As far as I can see, the "caught" and "wanted" messages below are exactly the same. Thought it may have been an issue with exception handling in 9.5, but my `test80_error_tests.sql` in my mimeo extension (https://github.com/omniti-labs/mimeo) passes in 9.5 without any issue.

```
not ok 1584 - Check that undoing partitions is prevented if subpartitions still exist
# Failed test 1584: "Check that undoing partitions is prevented if subpartitions still exist"
#       caught: P0001: Child table for this parent has child table(s) itself (partman_test.id_taptest_table_p0). Run undo partitioning on this table or remove inheritance first to ensure all data is properly moved to parent
# CONTEXT: SQL statement "SELECT undo_partition_id('partman_test.id_taptest_table', 20, p_keep_table := false)"
# PL/pgSQL function throws_ok(text,character,text,text) line 16 at EXECUTE
# DETAIL: 
# HINT: 
#       wanted: P0001: Child table for this parent has child table(s) itself (partman_test.id_taptest_table_p0). Run undo partitioning on this table or remove inheritance first to ensure all data is properly moved to parent
# CONTEXT: SQL statement "SELECT undo_partition_id('partman_test.id_taptest_table', 20, p_keep_table := false)"
# PL/pgSQL function throws_ok(text,character,text,text) line 16 at EXECUTE statement
# DETAIL: 
# HINT: 
```

**Comment by theory** [comment]
I don't think the test looks at the context string. Try leaving it out:

    SELECT throws_ok(
        'SELECT undo_partition_id(''partman_test.id_taptest_table'', 20, p_keep_table := false)',
        'P0001',
        'Child table for this parent has child table(s) itself (partman_test.id_taptest_table_p0). Run undo partitioning on this table or remove inheritance first to ensure all data is properly moved to parent',
        'Check that undoing partitions is prevented if subpartitions still exist'
    );

**Comment by keithf4** [comment]
Still fails. And explicitly shows a string difference now.
```
not ok 1584 - Check that undoing partitions is prevented if subpartitions still exist
# Failed test 1584: "Check that undoing partitions is prevented if subpartitions still exist"
#       caught: P0001: Child table for this parent has child table(s) itself (partman_test.id_taptest_table_p0). Run undo partitioning on this table or remove inheritance first to ensure all data is properly moved to parent
# CONTEXT: SQL statement "SELECT undo_partition_id('partman_test.id_taptest_table', 20, p_keep_table := false)"
# PL/pgSQL function throws_ok(text,character,text,text) line 16 at EXECUTE
# DETAIL: 
# HINT: 
#       wanted: P0001: Child table for this parent has child table(s) itself (partman_test.id_taptest_table_p0). Run undo partitioning on this table or remove inheritance first to ensure all data is properly moved to parent
```
It's looking for a full string match on the entire error message, which includes the CONTEXT, DETAIL & HINT. You can see that in the error I posted above. Both "caught" and "wanted" contain all the error sections.

Thought this sounded familiar
https://github.com/theory/pgtap/issues/78

Doesn't seem to be the same issue this time, though. And like I said, it's passing in 9.4.

**Comment by theory** [comment]
Okay, pasting your original report into TextMat, I get this diff:

    --- untitled 2
    +++ (clipboard)
    @@ -1,5 +1,5 @@
     P0001: Child table for this parent has child table(s) itself (partman_test.id_taptest_table_p0). Run undo partitioning on this table or remove inheritance first to ensure all data is properly moved to parent
     # CONTEXT: SQL statement "SELECT undo_partition_id('partman_test.id_taptest_table', 20, p_keep_table := false)"
    -# PL/pgSQL function throws_ok(text,character,text,text) line 16 at EXECUTE
    +# PL/pgSQL function throws_ok(text,character,text,text) line 16 at EXECUTE statement
     # DETAIL: 
    -# HINT: 
    +# HINT: 
    \ No newline at end of file

**Comment by keithf4** [comment]
FFS... stealth patch in 9.5 seems to have removed the keyword "statement" from the CONTEXT exception block. Which now makes this even more challenging to unit text :(

**Comment by theory** [comment]
Well, you might find [`throws_matching()`](http://pgxn.org/dist/pgtap/doc/pgtap.html#throws_matching.) more useful, then.

**Comment by theory** [comment]
Okay, gonna close, since #92 takes on the issue of context and hints.

**Comment by theory** [comment]
v0.96.0 released with this functionality. Thanks Jim!
