### ISSUE TITLE
functions_are() sees pgtap's functions

### ISSUE THREAD

**Issue by wttw** [theory/pgtap#97]
functions_are() isn't terribly useful at the moment, as it sees all the pgtap functions and so fails with "Extra functions: _expand_on, _rexists, ...".

I'm not sure what the fix is - it's convenient to have the pgtap functions in the path, so moving them to a schema not in the path wouldn't be great.

types_are() has a similar problem, but it's only a single extra type.

**Comment by theory** [comment]
Install pgTAP into its own schema, then don't test that schema.

**Comment by sheerun** [comment]
I bit me as well @theory Maybe you could mention it in installation description? (as well as command to do it, I'm not 100% sure what's the correct way to setup tests)

**Comment by theory** [comment]
CREAT SCHEMA IF NOT EXISTS tap;
    CREATE EXTENSION IF NOT EXISTS pgtap SCHEMA tap;

**Comment by sheerun** [comment]
Then I get "ERROR:  function plan(integer) does not exist" type of errors when testing public schema.

**Comment by theory** [comment]
Then in your test, put this line at the top:

    SET search_path TO tap,public;

Or prepend `tap.` to all the test function calls.

**Comment by sheerun** [comment]
Yet this causes original issue again, because pgtap searches for functions in both tap and public namespaces :)

**Comment by theory** [comment]
Yeah, so when you call those functions that search all that namespace, particularly `functions_are()` and `views_are()`, remove `tap` from the search path and prepend `tap.` to the function call. I've written tests like this:

    SELECT tap.plan(2);
    SELECT tap.functions_are(…);
    SET search_path TO tap,public;
    SELECT tables_are(…);
    SELECT finish();
